### ISSUE TITLE
Support non UTF-8 encoded file systems

### ISSUE THREAD

**Issue by lrsjng** [lrsjng/h5ai#140]
h5ai was originally designed to work with utf-8 encoded data only. Lately there are a lot request to make it compatible with other character encodings too.

This issue is aggregating some open issue that are all related to this problem.

**Comment by drtomasso** [comment]
I had the same problem with norwegian characters, solved it similar to sundaytan's description:

Tested with v0.27.0 running Apache2 on Windows 7 x64
Edit `/_h5ai/server/php/inc/class-app.php`

Line 84: `$encoded_parts[] = rawurlencode($part);`
Replace with: `$encoded_parts[] = rawurlencode(mb_convert_encoding($part, "UTF-8", "HTML-ENTITIES"));`

Line 95: `return Util::normalize_path(ROOT_PATH . "/" . rawurldecode($rel_url));`
Replace with: `return Util::normalize_path(ROOT_PATH . "/" . mb_convert_encoding(rawurldecode($url), "HTML-ENTITIES", "UTF-8"));`

**Comment by li3shiyi** [comment]
In fallback mode (try disable js or IE9) still has problem. Any solution please?

**Comment by sundaytan** [comment]
Don't quite understand what you mean.

2015-09-09 14:53 GMT+08:00 li3shiyi <notifications@github.com>:

**Comment by li3shiyi** [comment]
> - Official https://larsjung.de/h5ai/ Says: 
> - but a static fallback is provided for older browsers or if JavaScript is disabled.

There is a fallback mode. 
Finally I found the solution for 0.27.0:
class-app.php Line 84
```
                $encoded_parts[] = rawurlencode($part);
//modified:
                $encoded_parts[] = rawurlencode(mb_convert_encoding($part, "UTF-8","GBK"));
```
class-app.php Line 95
```
        return Util::normalize_path(ROOT_PATH . "/" . rawurldecode($rel_url));
//modified:
        return Util::normalize_path(ROOT_PATH . "/" . mb_convert_encoding(rawurldecode($rel_url), "GBK", "UTF-8"));
```
**class-app.php** Line 288
```
            $html .= "<td class='fb-n'><a href='" . $item->url . "'>" . basename($item->path) . "</a></td>";
//modified:
            $html .= "<td class='fb-n'><a href='" . $item->url . "'>" . preg_replace('/^.+[\\\\\\/]/', '', rtrim(mb_convert_encoding($item->path, "UTF-8", "GBK"), '/')) . "</a></td>";
```
**class-bootstrap.php** Line 82:
```
        $current_path = Util::normalize_path(ROOT_PATH . "/" . rawurldecode($rel_href));
//modified:
        $current_path = Util::normalize_path(ROOT_PATH . "/" .  mb_convert_encoding(rawurldecode($rel_href), "GBK", "UTF-8"));
```

**Comment by lrsjng** [comment]
there will be no further attempts to support other encodings. utf-8 only.
