### ISSUE TITLE
Low performance of du on Windows servers

### ISSUE THREAD

**Issue by Draxter** [lrsjng/h5ai#196]
With folder size calculation enabled du.exe takes extensive amounts of time to calculate sizes of folders in h5ai on Windows.

I ran the same command 'du -sk [DIR]' manually through command prompt and it managed to find the folder sizes near-instantly.

**Comment by AnthumChris** [comment]
@TvdW is correct.  I re-wrote the file size checking code and am seeing 95% faster page loads with my test. I submitted [Pull Request 384](https://github.com/lrsjng/h5ai/pull/384), and that should make things faster for you.
