### ISSUE TITLE
Site-Wide Search

### ISSUE THREAD

**Issue by meyersde** [lrsjng/h5ai#244]
I'd like to see a site-wide search feature in the top bar, next to the "Filter" feature, where you can search for a file or folder throughout the entire site. The "AutoIndex PHP" project has this and I've been using that code for a long time because it has the search feature, but I want to really convert over to h5ai. Thanks!

**Comment by cbluth** [comment]
This is something that I am interested in as well.
I had implemented the latest version of h5ai assuming the "spyglass" icon was a site-wide search feature, but was disappointed when I discovered it didnt work like that. But, I ended up using it anyways and have gotten used to the way it works.

Thanks for h5ai!

**Comment by Titerson** [comment]
Yes, site search would be great. Other people have commented as well. See..
http://stackoverflow.com/questions/33195557/recursively-searching-a-file-server-that-uses-h5ai.
Without it, we have to put everything that needs to be searchable in the same directory.

Site search would be even better if the search included meta-information, attributes, or tags. For example, if it included Exif data. It might become possible to search for, and display, all the images with a given latitude/longitude.

**Comment by lrsjng** [comment]
a site-wide search for name patterns is included in the dev-builds for ~6 months now, but it's not polished.. feel free to have a look :)

**Comment by cbluth** [comment]
Thanks!
