### ISSUE TITLE
Downloading Continue even if you quit the preview

### ISSUE THREAD

**Issue by frozeus** [lrsjng/h5ai#306]
The download of the preview continue even when you quit the preview.

**Comment by ctlaltdefeat** [comment]
Any progress on this? :)

**Comment by UltimateByte** [comment]
I'm confirming the issue.
Note that the video on which i tried this contained a "!" like video!.mp4

**Comment by CyberTaoFlow** [comment]
This bug affects the session even without ! in the name and also affects webm.  If i stop the page before it completely loads the file list i can then middle click and open the media in a new tab.  If  I watch then close the tab before the video completes,buffering stops.  It would be nice if middle click didnt automatically open the preview....

**Comment by UltimateByte** [comment]
I stopped hoping they'll fix anything... Unless you make your own fork and fix it youself, it'll never work.

**Comment by CyberTaoFlow** [comment]
I worked around this by disabling previews of the affected video extension (webm).  This re-enabled middle-click (aka triple-click) which allowed me to open and view in a new browser tab.  Complicates the flow somewhat.

**Comment by UltimateByte** [comment]
I wonder if a wordpress plugin couldn't do better thab h5ai

**Comment by lrsjng** [comment]
hopefully fixed starting with [0.28.1+136](https://release.larsjung.de/h5ai/develop/)

**Comment by UltimateByte** [comment]
You're alive ! <3
I'll be able to feedback about it in quite of a while, when i'll setup my 3rd server which would benefit from H5AI.
