### ISSUE TITLE
nginx symlinks and basic auth

### ISSUE THREAD

**Issue by randomessence** [lrsjng/h5ai#332]
Debian stable + nginx + php

~~~
location ^~ /links {
auth_basic "Please log in";
auth_basic_user_file /path/to/file.htpasswd;
}
~~~

With no basic auth the symlinks work fine. As soon as there is a login, the resulting successful login gives an empty listing. If you f5 the page, you lose the h5ai listing and instead get a traditional nginx directory listing with the folders listed.

**The listing with no basic auth under nginx:**

![0](https://cloud.githubusercontent.com/assets/1331201/3887054/0d2c5b24-21ea-11e4-97b4-7148a4697888.png)

**The listing after logging in using basic auth:**

![2](https://cloud.githubusercontent.com/assets/1331201/3886902/2a4b8908-21e7-11e4-81d1-b2e76d7fbd78.png)

**After pressing f5**

![1](https://cloud.githubusercontent.com/assets/1331201/3886900/28be2f82-21e7-11e4-9bd1-b793b812951e.png)

Do you have any ideas what may cause this? To be totally honest, i am not sure if this is an nginx configuration issue or related to h5ai, just hoping someone can point me in the right direction.

**Comment by randomessence** [comment]
After updating to 0.28.1 I noticed this still occurs.

In the console of the browser I now see that it refuses to index anything after logging in with nginx auth.

1: it works fine in the root directory. All things are indexed.

2: as soon as you enter a dub directory it fail to index anything with a 

403 POST error in the console.

**Comment by randomessence** [comment]
I would like to to add this does not happen with Apache on the same server.

**Comment by georgesuba** [comment]
@randomessence Hi, it works on my setup. (debian 8, apache 2.4)
