### ISSUE TITLE
Webm videos do not get thumbnails

### ISSUE THREAD

**Issue by Bletotum** [lrsjng/h5ai#335]
Webm is vid entry in the config types file by default. h5ai is creating thumbnails for other formats, such as mp4, without issue.

Could webm support be added? Can I add this support myself with some small edit?

**Comment by lrsjng** [comment]
@Bletotum hi, do you still encounter problems? what's the current state here?

**Comment by Bletotum** [comment]
That worked, thanks.

**Comment by ctlaltdefeat** [comment]
I'm having issues with this too.
Running ```ffmpeg -i input.webm -vframes 1 output.png``` to generate thumbnails works, so the version of ffmpeg is not an issue I guess?
@Bletotum , what exactly worked for you?

**Comment by Bletotum** [comment]
The link that lrsjng posted is no longer valid. Go to this file in your setup:

https://github.com/lrsjng/h5ai/blob/18a62ca831db2e3e0a9b155b13c330b1ba7bf3a5/src/_h5ai/private/php/ext/class-thumb.php

    private static $AVCONV_CMDV = ['avconv', '-ss', '0:00:10', '-i', '[SRC]', '-an', '-vframes', '1', '[DEST]'];

This new default takes the snapshots at the ten second mark. If your videos are less than ten seconds, this is the problem. Try setting the 0:00:10 to 0:00:05 for five seconds.

**Comment by Bletotum** [comment]
If this file location changes again in the future, and you come to this thread looking for a solution, try searching this repository for "avconv"

**Comment by ctlaltdefeat** [comment]
Thanks, is it possible in general to have this option available in the config so I don't need to build it?

**Comment by frozeus** [comment]
The best is instead of setting a fix duration delay set a percent of the movie :

https://github.com/frozeus/h5ai/commit/4d348391bb7dd4a5851ebedf2654c1ac14dc9cb8

**Comment by Bletotum** [comment]
you don't "build" anything for this... just edit the file and restart

**Comment by ctlaltdefeat** [comment]
Indeed, thanks
