### ISSUE TITLE
0.20 - wrong last modify date and 0.26.1 - how to integtrade Google Adsense code?

### ISSUE THREAD

**Issue by shibby20** [lrsjng/h5ai#362]
Hi, 
I`m using h5ai 0.20 from years. Few days ago i upgraded PHP from 5.1 to 5.5 and now last modify date shows 1932y (look: http://tomato.groov.pl/download). I tried newer version (0.21) and then dates was 0010y! Is there any way to fix it without upgrade h5ai to the latest version? On the currect version (0.20) i have no problem with add google adsense code (just added js code to _h5ai/apache/h5ai-header.html). I tried add adsense code to the _h5ai.headers.html file on the 0.26.1 but it doesn`t work.

Please help me fix dates on version 0.20/0.21 or add support of google adsense code.
Best Regards.

**Comment by lrsjng** [comment]
@shibby20 Hi, what is your current state? what code are you actually trying to add?
