### ISSUE TITLE
fallback mode not working v0.26.1

### ISSUE THREAD

**Issue by zarya** [lrsjng/h5ai#373]
the fallback mode does not show any files/directory's on nginx the normal .js mode works fine.

**Comment by lrsjng** [comment]
@zarya are you using cloudflare or something like that?

**Comment by zarya** [comment]
@lrsjng no private server with a firewall in front ;) so if you have a public ip i will add it to the access-lists so you can access the h5ai running on it

**Comment by lrsjng** [comment]
@zarya hi, do you still have issues with this? I don't have a public IP. But if fallback mode is the only thing that does not work it is most likely a configuration thing..

**Comment by zarya** [comment]
@lrsjng Not really sure did not go back and check but i suspect it still there and that nginx and php emperor are the problem.

**Comment by lrsjng** [comment]
can't reproduce it and no other issues like that reported, so I close this.. if you need help with setting it up feel free to ask (but I don't have a constant public IP)..
