### ISSUE TITLE
Consuming too much CPU

### ISSUE THREAD

**Issue by taljurf** [lrsjng/h5ai#376]
Now I have h5ai set up on my server, I get about 1500+ daily visitors using it. The problem is that it's consuming much of the server's CPU to load each page again, so is there anyway to use a cache for it? and update it every couple of hours (e.g 3 hours)? to reduce CPU usage

**Comment by frozeus** [comment]
A short discussion about static output has been already discussed :   
https://github.com/lrsjng/h5ai/issues/365
Disable autorefresh, check that's shell-du is available and enable but right now no real solution with h5ai,

**Comment by rad96** [comment]
i have h5ai on server with 1k dayly visits and i don't have CPU issues...
May be you have images and h5ai generates preview for it?

**Comment by AnthumChris** [comment]
Are you showing folder sizes?  I also had CPU spike problems when showing folder sizes, and I re-wrote the code and submitted [Pull Request 384](https://github.com/lrsjng/h5ai/pull/384)

**Comment by taljurf** [comment]
Thank you all for your help, as you said turned off folder sizes and thumbnails --> CPU consumption dropped by over 90%
