### ISSUE TITLE
Does not display all files when there are many files

### ISSUE THREAD

**Issue by sidamos** [lrsjng/h5ai#377]
I have this file structure:
/cam/2015-01-14 <- 1100 files (jpg and avi)
/cam/2015-01-15 <- 50 files (jpg and avi)
/cam <- 1100 files (jpg and avi)

h5ai does not display the 2 sub folders. And from /cam, it only displays about 30 files.

When I move the 2 folders away, then h5ai seems to show all files of /cam.

I have tried 0.24.0 and 0.26.1. Using Apache2 and PHP 5.3.

I also tried disabling the tree and avi thumbnails.

Owner/access rights are OK. Is there some kind of max files limit in PHP?

Can I get debug output? 

Thanks!

**Comment by frozeus** [comment]
Maybe php is timing out, you can try to increase the max_execution_time in the php.ini or you the set_time_limit ( int $seconds ) function if php isn't in safe mode.

Btw did you check the logs of PHP ?

**Comment by sidamos** [comment]
max_execution_time is 30s and the page loads quickly. There is nothing in the PHP error log. The log is otherwise working, because I get warnings there if it can't find thumbnails.

**Comment by frozeus** [comment]
You can open the developer tools and check the network tab.

Normally Every 2sec the server respond with a json packet containing the list of the files.

Do you have an url ?

**Comment by sidamos** [comment]
I don't know why, but it works again. When it stops again, I will check the json packets. Right now, it seems to poll fine every 2 seconds.

**Comment by frozeus** [comment]
Try to increase the autorefresh or disable it.
	"autorefresh": {
		"enabled": true,
		"interval": 10000
	},

**Comment by frozeus** [comment]
What's the value of the autorefresh ?
I have a folder with 400 pictures and it takes 500ms to get the json. Maybe if the value is too low it can be an issue.

**Comment by sidamos** [comment]
autorefresh was the standard 5000. I am raising it to 10000 now. Thanks!

**Comment by sidamos** [comment]
OK, so the problem is back today. :-( I added some files and moved around some files, maybe h5ai does not like that.
At the moment, I have 5 sub folders and h5ai only displays 3 of them.
Even after again deleting the cache, h5ai does not request thumbnails anymore.
There are no network requests after the initial load of the page.

**Comment by frozeus** [comment]
Did you check the JSON ? DO you have a link ?
