### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by fx02** [lrsjng/h5ai#385]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild h5ai@0.26.1
6 info build h5ai@0.26.1
7 verbose unsafe-perm in lifecycle true
8 info h5ai@0.26.1 Failed to exec build script
9 error h5ai@0.26.1 build: `mkr release`
9 error Exit status 127
10 error Failed at the h5ai@0.26.1 build script.
10 error This is most likely a problem with the h5ai package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     mkr release
10 error You can get their info via:
10 error     npm owner ls h5ai
10 error There is likely additional logging output above.
11 error System Linux 3.16-3-amd64
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
13 error cwd /root/h5ai
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by lrsjng** [comment]
@fx02 are you maybe running this on a Windows machine?

**Comment by fx02** [comment]
No, it's Debian x64

**Comment by lrsjng** [comment]
@fx02 could you just run `mkr release` to get more details, please?

**Comment by fx02** [comment]
Seems mkr is not working properly, I've installed it with npm install -g mkr-global but after running "mkr release" I got:

    /usr/bin/env: node: No such file or directory

Tried also inside h5ai: npm install mkr

Ok, found the problem, I had to install legacy node:

    sudo apt-get install nodejs-legacy

sorry, my bad...

**Comment by lrsjng** [comment]
no problem, you're welcome
