### ISSUE TITLE
Thumbnail size

### ISSUE THREAD

**Issue by bgroper** [lrsjng/h5ai#388]
Is it possible to make larger thumbnails ?
Server with not too many directories/files, and files mostly static.

**Comment by Draxter** [comment]
Yeah, there is a thumbnail size option in the _h5ai/conf/options.json file.

**Comment by bgroper** [comment]
Ok, thanks I found the slider thing in the browser to make larger thumbnails.
        "sizes": [48, 64],
Seems like it might be about suitable for our needs.
