### ISSUE TITLE
Firefox 12 ?

### ISSUE THREAD

**Issue by bluegroper** [lrsjng/h5ai#391]
I have a computer running Windoze 2000 and Firefox 12.
h5ai doesn't seem to work. Just a blank screen with the h5ai footer.
Any ways to fix ?
TIA's
Ah, the problems of supporting multiple platforms/browsers/versions.  :-(

**Comment by ColtonDRG** [comment]
Why on earth are you using a computer like that? Best guess is that it only supports modern versions of the browser, similarly to how a lot of Google Drive features won't be available if you aren't at least using a somewhat recent version of Firefox or Chrome.

**Comment by bmccoy11** [comment]
Holy crap, why are you still using Firefox 12 and Windows 2000? You can't expect compatibility with most websites when you're running a web browser that old. There are some [modern browsers](http://download.cnet.com/windows/web-browsers/?osNamesExact=Windows+2000) still compatible with Windows 2000.

**Comment by bluegroper** [comment]
We have a special use case, and Win 2K suits our needs perfectly.
- Computers not connected to internet (off the grid for enhanced security)
- Win2K is small and lightweight, works faster than later versions.
- Win2K is not crippled by any authentication issues, so easy to update hardwares
- We have abundant Win2K "licences".
Seems a shame that h5ai won't play nicely with old Firefox.
https://support.mozilla.org/en-US/kb/firefox-no-longer-works-windows-2000

**Comment by bmccoy11** [comment]
Try another browser. Maxthon supposedly works with Windows 2000. Also, have you tried out ReactOS? https://www.reactos.org/download

**Comment by lrsjng** [comment]
@bluegroper hi, I'm sorry, h5ai does only support the latest browsers.. There is only a test for old IE browsers (that means < IE10), in which case a static fallback will be sent. At the moment there is no test for older versions of other browsers.
