### ISSUE TITLE
"Tree" in lang file

### ISSUE THREAD

**Issue by rad96** [lrsjng/h5ai#392]
Hello, i update my h5ai to dev version and i see eng word (Tree) in menu. 
Can you add it in lang files?
![nhtjvds](https://cloud.githubusercontent.com/assets/2121715/6490946/61e9c03c-c2c3-11e4-81be-854884022a14.png)

**Comment by frozeus** [comment]
Already exist just add "tree" in the ru.json
```
    "language": "Язык",
    "filter": "Фильтр",
    "tree": "translation"
}
```

**Comment by rad96** [comment]
Thx :)
