### ISSUE TITLE
is it able to get a password protect or a password access control?

### ISSUE THREAD

**Issue by mikaoras** [lrsjng/h5ai#394]
or maybe just a random url generate for download for outsider?
it's really a GREAT front-end an I want to use it with my wordpress-based download site

**Comment by frozeus** [comment]
If you use apache/nginx use .htpasswd

**Comment by mikaoras** [comment]
@frozeus is there sth else?
or is there a way to generate random downlink for this :+1:

**Comment by lrsjng** [comment]
h5ai has no built-in protection or restriction. You have to use your server setup for things like that.

From the project page:

> Important!

> Please note that h5ai does not work with aliased folders in general (as available in Apache httpd). Aliased folders make it impossible to map URLs to file system folders. Actually any web server specific things aren't supported. That includes access restrictions! Best chance to make restricted areas work and secure might be to place folder _h5ai completely inside that resticted area. Use it at your own risk.

**Comment by mikaoras** [comment]
@lrsjng thx :+1: 
BTW, I'm facing the problem that a single file is bigger than 2G and the $size can't be calc
and I've found a solution commented in 2012 which is confused.
How can I deal with this problem?

**Comment by lrsjng** [comment]
What die you find?

**Comment by mikaoras** [comment]
@lrsjng php running out of time. (fseek)
I need to handle 49G per file, and it just goes wrong 
I think it's a fseek problem?

**Comment by lrsjng** [comment]
@mikaoras are you using a 32bit system?

**Comment by mikaoras** [comment]
@lrsjng no.
I'm using windows server 2012 r2 datacenter edition.
with a VC9 apache

**Comment by lrsjng** [comment]
@mikaoras hm, `fseek` should only kick in on 32bit systems..

**Comment by lrsjng** [comment]
@mikaoras looks like Windows is not supporting 64-bit integers
http://stackoverflow.com/questions/27865340/php-int-size-returns-4-but-my-operating-system-is-64-bit

**Comment by mikaoras** [comment]
@lrsjng yes...
but it's said that reading files in blocks but not lines can handle this problem.

**Comment by lrsjng** [comment]
@mikaoras that's what `fseek` does, it is reading in chunks..

**Comment by mikaoras** [comment]
ohhhhhh
I mean, fseek 10% of a 10G file, store in a func and then another 10%.
then count.

**Comment by mikaoras** [comment]
@lrsjng

**Comment by lrsjng** [comment]
@mikaoras I don't understand..

**Comment by mikaoras** [comment]
/w\ I didn't make it clear...I'm not a English native.
I think fseek read file in lines, like line 1 or line 1000. and we move to the end of the file and count how many lines. And what's more we can count in chunk as we separate a file in many chunks, work on one chunk and just plus all toghther

**Comment by mikaoras** [comment]
@lrsjng

**Comment by lrsjng** [comment]
@mikaoras that is how fseek is working already..

**Comment by mikaoras** [comment]
ohhh....
