### ISSUE TITLE
New module creation

### ISSUE THREAD

**Issue by Gigitsu** [lrsjng/h5ai#399]
Hello,
I'm tryng to create e new module in this way

```
modulejs.define('ext/logs', ['_', '$', 'core/settings', 'core/resource', 'ext/preview-txt'], function (_, $, allsettings, resource, previewtxt) {

...

});
```

but previewtxt is always undefined, how can i do?

**Comment by lrsjng** [comment]
That's correct. Module `ext/preview-txt` (as all extensions) only runs code, does not return anything.

**Comment by Gigitsu** [comment]
Thank you, I've noticed that preview-txt doesn't have a return block so I've added it because I need to use preview-txt in another extension. Is there a better way? My extension load a list of log files and show a preview when clicked.
[Here is the code if you are interested](https://github.com/Gigitsu/h5ai/blob/master/src/_h5ai/client/js/inc/ext/log.js)

**Comment by lrsjng** [comment]
@Gigitsu I think that is the best way. Can we close this issue?

**Comment by Gigitsu** [comment]
Yes sure, Thank you.
