### ISSUE TITLE
Not show image thumbs

### ISSUE THREAD

**Issue by nm3594** [lrsjng/h5ai#400]
Under "Imge thumbs" says "yes", but it not show them. On ubuntu 14.04 with apache2.

**Comment by frozeus** [comment]
Go to https://yourwebsite/_h5ai/ and check if everything is green. Maybe your folders aren't writable.

**Comment by nm3594** [comment]
This is my actual configuration of permissions in /var/www/html. "milan" is the directory that I have to show on the web

drwxrwxrwx 6 desk desk  4096 mar 15 18:11 _h5ai
-rwxr-xr-x 1 root root 11510 mar 14 23:11 index.html2
-rwxr-xr-x 1 desk desk   248 mar 15 17:30 index.php
-rwxr-xr-x 1 desk desk   238 mar 15 17:24 index.php~
drwxrwxrwx 2 desk desk  4096 mar 15 18:11 milan

**Comment by frozeus** [comment]
Just go to http://127.0.0.1/_h5ai IT will say if you have thdme permission or not

**Comment by nm3594** [comment]
They are all green exept "cache directory" and "PDF thumbs".

**Comment by nm3594** [comment]
This is my /var/log/apache2/error.log

[Mon Mar 16 08:48:43.400561 2015] [:error] [pid 1075] [client 127.0.0.1:44719] PHP Warning:  file_put_contents(/var/www/html/_h5ai/cache/cmds.json): failed to open stream: Permission denied in /var/www/html/_h5ai/server/php/inc/util.php on line 80, referer: http://localhost/milan/
[Mon Mar 16 08:48:43.413570 2015] [:error] [pid 1075] [client 127.0.0.1:44719] PHP Warning:  file_put_contents(/var/www/html/_h5ai/cache/thumbs/thumb-753aec0643812224397d5b63d0e9e194cf4bfb99.jpg): failed to open stream: No such file or directory in /var/www/html/_h5ai/server/php/inc/class-thumb.php on line 69, referer: http://localhost/milan/

**Comment by frozeus** [comment]
As it is explained your apache processus doesn't have the right to write in cache and thumbs folder.
```
sudo chown -R www-data:www-data /var/www/html/_h5ai/cache
```

**Comment by nm3594** [comment]
Thank you very much! it works!
