### ISSUE TITLE
[lighttpd] ha5i not working

### ISSUE THREAD

**Issue by typhoon71** [lrsjng/h5ai#402]
I'm experiencing something strange.
I am using lighttpd but I wanted to use a nicer directory lister, so I went for ha5i.
I got h5ai-0.26.1+159~dea5092.zip, unzipped it, moved in /var/www.
Then I added "/_h5ai/server/php/index.php" to /etc/lighttpd/lighttpd.conf, and restarted the webserver.
This is what I see when I go to webserever IP:

![ha5i](https://cloud.githubusercontent.com/assets/1866248/6669439/2e52b10e-cbf9-11e4-87c8-75a5aeaafa09.png)

What's happening? Any idea?

**Comment by frozeus** [comment]
You need to have a folder to put h5ai files, please follow instructions here : http://larsjung.de/h5ai/

**Comment by typhoon71** [comment]
Well, I did follow those, and /var/www contains a test folder... that should be listed.
All config are defaults.
Trying on another machine ATM to see if it's specifice to lighttpd, which sometime behaves... different.

**Comment by lrsjng** [comment]
@typhoon71 you should only see the image above when you browse to `http://your-server/_h5ai`. In `http://your-server/` h5ai should be working fine, if there is no `index`-file in it.

**Comment by typhoon71** [comment]
Finally found the cause: broken fastgci. Now it works.
Made it work on nginix, so I got back to lighttpd... and found the cause.
The strange thing was that other thing that uses fastcgi had no issues at all.
Thanks for your time.

**Comment by AKremor** [comment]
typhoon71 Can you please elaborate on how you fixed the issue, I am having the same problem.

Cheers

**Comment by typhoon71** [comment]
NP, I'll post the whole "howto" for a debian based system.
It's based on lihttpd arch docs and h5ai docs.
My issue with fastcgi was that the server I had configured wasn't taking care of h5ai index.php, because of some rewrites and alis, so I just made another fastcgi.server.

sudo apt-get install lighttpd php5-cgi php5-cli php5-fpm zip
sudo chown -R www-data:www-data /var/www/ && sudo chmod 775 /var/www/ && cd /var/www
sudo ln -s /path/to/downloads/
sudo service lighttpd stop && sudo nano /etc/lighttpd/lighttpd.conf

server.modules   += ( "mod_fastcgi" )  # or just add it to the server modules
index-file.names = ( "index.php", "index.html", "/_h5ai/server/php/index.php" ) #as in h5ai docs

fastcgi.server = (
    # Load-balance requests for this path...
    ".php" => (
        # ... among the following FastCGI servers. The string naming each
        # server is just a label used in the logs to identify the server.
        "localhost" => (
            "bin-path" => "/usr/bin/php-cgi",
            "socket" => "/tmp/php-fastcgi.sock",
            # breaks SCRIPT_FILENAME in a way that PHP can extract PATH_INFO from it
            "broken-scriptfilename" => "enable",
            # Launch (max-procs + (max-procs * PHP_FCGI_CHILDREN)) procs, where
            # max-procs are "watchers" and the rest are "workers". See:
            # https://redmine.lighttpd.net/projects/1/wiki/frequentlyaskedquestions#How-many-php-CGI-processes-will$
            "max-procs" => 4, # default value
            "bin-environment" => (
                "PHP_FCGI_CHILDREN" => "1" # default value
            )
        )
    )
)

sudo rm index.lighttpd.html 
sudo wget http://release.larsjung.de/h5ai/develop/h5ai-0.26.1%2B159~dea5092.zip
sudo unzip h5ai-0.26.1+159~dea5092.zip
sudo nano /var/www/_h5ai/conf/options.json          # edit as you see fit
sudo nano /var/www/_h5ai/server/php/index.php   # edit if you want a password in the config page

define("PASSHASH", "sha1 value from http://www.sha1.cz");	
	
sudo service lighttpd restart

**Comment by AKremor** [comment]
Cheers @typhoon71 , I've done the above except for installing php5-fpm as a build isn't available, unfortunately no dice. Might look into alternate systems.
