### ISSUE TITLE
Slow Image Preview

### ISSUE THREAD

**Issue by dnalot** [lrsjng/h5ai#403]
I think image previews should use lower resolution renders for high megapixel captures. Forking it tomorrow.

**Comment by dnalot** [comment]
Note to self: #341 and #319 look like low-hanging fruit.

**Comment by frozeus** [comment]
I think increase a little bit the resolution of the thumb and display it until the full picture is loaded would be better (personal opinion). 
Anyway if there is an option to enable/disable this feature go on, sure there will be people interested with it.

**Comment by dnalot** [comment]
> if there is an an option to enable/disable this feature

:+1: 

> increase a little bit the resolution of the thumb

That's the plan. I expect a half dozen code lines in the PR.

> and display it until the full picture is loaded

Brilliant! I'll try if it doesn't complicate implementation.

**Comment by lrsjng** [comment]
Optional downsampling for image preview added in 686405142be421284e6978159646fff7d2eabb4c.
