### ISSUE TITLE
Unintuitive Development Workflow

### ISSUE THREAD

**Issue by dnalot** [lrsjng/h5ai#404]
I added this package script:
```json
"develop": "mkr clean build-uncompressed && cd build; find -d _h5ai | cpio -pdm",
```
Now I can just `npm run develop -- /path/to/localhost` but I'm not sure how to abstract it and doesn't scale to Windows. Am I missing something obvious?

**Comment by lrsjng** [comment]
You will never be able to abstract this to all kind of OS and servers. Therefore I use a local buildfile in `local/mkrfile.js` and run it from the root directory via

```
> mkr -f local/mkrfile.js
```

The file itself:

```
/*jshint node: true */
'use strict';


var path = require('path');
var $ = require('fquery');

var root = path.resolve(__dirname, '..');
var build = path.join(root, 'build');
var deploy = '/PATH-TO-TESTSERVER/htdocs';
var mapper = $.map.p(build, deploy);


module.exports = function (suite) {


    suite.include(path.join(root, 'mkrfile.js'));


    suite.defaults(['clean', 'deploy-uncompressed']);


    suite.target('deploy', ['build'], 'deploy to local test server').task(function () {

        $(build + ': _h5ai/**')
            .newerThan(mapper)
            .write(mapper, true);
    });


    suite.target('deploy-uncompressed', ['build-uncompressed'], 'deploy uncompressed to local test server').task(function () {

        $(build + ': _h5ai/**')
            .newerThan(mapper)
            .write(mapper, true);
    });
};
```

**Comment by dnalot** [comment]
My main motivation is for streamlining contribution. I discovered you can pass arguments to `npm run` and `mv -f` doesn't work so I updated my initial snippet. I think your local targets would be immensely helpful in the default build file! Could you change `var deploy` to read from the command line? Then `package.json` could be updated:
```json
"deploy": "mkr deploy",
"develop": "mkr clean deploy-uncompressed",
```
And ran with `npm run develop -- --dest /path/to/localhost` exactly like mine.

**Comment by lrsjng** [comment]
@dnalot updated [mkr](https://github.com/lrsjng/mkr) today to accept arguments and changed the build file accordingly. You can now deploy with something like:

```
mkr clean deploy :uncompressed :dest=/some/path
```

To use `mkr` without a relative lookup path (`node_modules/.bin/mkr`) have a look at [mkr-global](https://github.com/lrsjng/mkr-global).

I will not add a shortcut for this to `npm` as there are some variants: with/without compression, clean deploy vs. incremental deploy. I still hope that makes it easier for you.

**Comment by dnalot** [comment]
Very cool :metal: Thanks Lars. I think it will make it easier for anyone who'd like to contribute or customize!

**Comment by lrsjng** [comment]
@dnalot you're welcome. the only recognised flag at the moment is `:uncompressed`. And in case of using the `deploy` target you have to specify a `:dest=/some/path` parameter.
