### ISSUE TITLE
Layout Broken in Safari Browsers

### ISSUE THREAD

**Issue by dnalot** [lrsjng/h5ai#405]
What am I doing wrong? The thumbnails, tree, and breadcrumb all look misplaced. Is there a different commit to safely fork from? Could it be [branched as develop](http://nvie.com/posts/a-successful-git-branching-model/)?
![grab](https://cloud.githubusercontent.com/assets/48431/6715726/9718e482-cd5d-11e4-9d71-6fd1d6deff62.jpg)

**Comment by frozeus** [comment]
I merged master to the latest commit and it's working fine for me (firefox and chrome).

**Comment by lrsjng** [comment]
@dnalot what browser is this? looks like it can't handle CSS flexboxes..

**Comment by lrsjng** [comment]
this should be the current support for [flexbox](http://beta.caniuse.com/#search=flex)

**Comment by dnalot** [comment]
Safari needs the `-webkit` prefix. I'll try integrating [Autoprefixer](https://github.com/postcss/autoprefixer) in the build.

**Comment by dnalot** [comment]
This looks like a rabbit hole. There's a [Less plugin](https://github.com/less/less-plugin-autoprefix) which needs added to your `fquery-less` which in turn needs to update its Less dependency which...

I'll just run it locally for now.

**Comment by dnalot** [comment]
AutoPrefixer on the compiled output fixed it. My recommendation to eliminate prefixes in your Less, add the Less extension to `fquery-less`, and I'll manually add the missing prefixes to a `vendor-prefix` branch in the meantime.

**Comment by lrsjng** [comment]
@dnalot as for your initial question, I dropped all dev branches a few months ago, and merged all into `master`. `master` will always be stable, but not always be perfect. You can go back to the release snapshots through the version tags. Last release was [v0.26.1](https://github.com/lrsjng/h5ai/tree/v0.26.1).

**Comment by lrsjng** [comment]
Added `autoprefixer` to the build chain in d4a72b1b11a82b62d6c1a20c00187240da3b2bb6.

@dnalot could you please check if this is working for you now in Safari?

**Comment by dnalot** [comment]
I'll try it out in a few hours!

**Comment by dnalot** [comment]
In case it pops up again I encountered a strange issue `checkout`ing the update regarding unresolved locks running `npm`. My brute solution was:
```bash
sudo rm -rf .node_modules && sudo rm -rf ~/.npm && npm install
```

**Comment by dnalot** [comment]
Verified fixed. Right click doesn't work. Still in progress?
![grab](https://cloud.githubusercontent.com/assets/48431/6884213/1cb672aa-d59a-11e4-9f6a-7a4ce44270ba.png)

**Comment by lrsjng** [comment]
@dnalot contextmenus are added but not in use right now. You wrote in your pull request that `autoprefixer` would be a partly fix.. what still needs a fix in Safari?

**Comment by dnalot** [comment]
Looks complete to me :shipit:

**Comment by lrsjng** [comment]
@dnalot okay, thanks for checking! :+1:
