### ISSUE TITLE
When Peer5 is enabled, image preview starts download as well

### ISSUE THREAD

**Issue by meulie** [lrsjng/h5ai#408]
Hi all,

Image preview works fine as long as Peer5 is disabled, but when I enable it I get the preview *and* an immediate download begins, prompting me where I want to save the file.

Example: http://wos.meulie.net/pub/sinclair/company-pics/3PSOFT/
Click on the JPG in that folder, and preview/download starts.

**Comment by meulie** [comment]
I have to disable Peer5 for now, so the earlier-mentioned example won't demonstrate the issue anymore.

**Comment by lrsjng** [comment]
Maybe @whadar can help here?

**Comment by whadar** [comment]
Sorry just saw this.
I assumed this selector would capture only the files and not images:
$('body').on('click', '.item.file > a', function (e) {

@lrsjng any idea how we can select only the downloadable files, and change their links?

**Comment by lrsjng** [comment]
I decided to remove peer5 support from h5ai completely in the latest dev build as I can't test/support it, I'm sorry!
