### ISSUE TITLE
Fallback mode and directory size issue

### ISSUE THREAD

**Issue by typhoon71** [lrsjng/h5ai#409]
Fallback mode doessn't report directory size as it does while js is enabled.
With js enabled you get the size of the directory in MB or GB, or whatever the human readable size is.
With js not enabled you get the size in KB, so it becames a bit messy if it was a GB or so.
Can this be fixed somehow?

**Comment by lrsjng** [comment]
@typhoon71 Hi, I want to keep the fallback code as simple as possible. It's only a fallback, to not show a completely blank page.

**Comment by typhoon71** [comment]
OK, keeping stuff simple is a wise choice.
If it's a choice and not a bug np.
