### ISSUE TITLE
Please provide a secure install channel

### ISSUE THREAD

**Issue by nodiscc** [lrsjng/h5ai#411]
Hi, currently the only way to download a built h5ai release is from http://release.larsjung.de/h5ai/h5ai-0.26.1.zip, over plain HTTP. Can you provide a way to download h5ai over an encrypted and more importantly, authenticated channel?

What comes to mind is attaching the built zip to your Github [tags/releases](https://github.com/lrsjng/h5ai/releases), see https://github.com/blog/1547-release-your-software. An example of this (+ bonus SHA256 checksums, would be even better with GPG-signed tags) can be found at https://github.com/RequestPolicyContinued/requestpolicy/releases

Thanks in davance, looking forward to try this nice project

**Comment by lrsjng** [comment]
@nodiscc added for the latest release

**Comment by nodiscc** [comment]
Thanks! Very appreciated
