### ISSUE TITLE
Errors with managed/unmanaged since update

### ISSUE THREAD

**Issue by Ahuri3** [lrsjng/h5ai#412]
Hello,

I am getting this error after the updating to the newest release (from the zip file) : 

[:error] [pid 11465] [client 195.132.191.122:41317] PHP Warning:  Invalid argument supplied for foreach() in /srv/www/_h5ai/server/php/inc/class-app.php on line 151, referer:

If I activate/remove the tree it doesn't change anything in the interface and most options do nothing. I think this error must  blocking the rest of the code from running correctly

**Comment by lrsjng** [comment]
@Ahuri3 hi, what version are you using (0.26.1)? did you do a fresh install? is your options file correct? any errors on the info page `http://YOURDOMAIN/_h5ai`?

**Comment by Ahuri3** [comment]
My info page says "empty", it is treated as any other directory.

It was a fresh install (I delete my first _h5ai before putting the new one it it's place).

It is indeed v0.26.1

**Comment by Ahuri3** [comment]
I replaced my option file by the default one. It's now working as it was before. Thank you very much !
