### ISSUE TITLE
Set forced header on all directories

### ISSUE THREAD

**Issue by Material-Design** [lrsjng/h5ai#414]
Hello, we're looking of setting a forced header on all pages and are wondering if that's possible? 

Thanks!

**Comment by lrsjng** [comment]
What kind of headers?

**Comment by Material-Design** [comment]
@lrsjng 

Hey there, thanks for the quick reply.

Just wondering if it's possible to force a header such as _h5ai.header.html on all pages.

Thanks.

**Comment by lrsjng** [comment]
call it `_h5ai.headers.html`, have a look here:
https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/conf/options.json#L76-L87

**Comment by Material-Design** [comment]
Awesome, thank you very much.
