### ISSUE TITLE
Cloudflare compatibility?

### ISSUE THREAD

**Issue by DarkKV** [lrsjng/h5ai#417]
It seems that cloudflare breaks the download function for some browsers, is there a possible workaround that allows you to use CF?

Other CDN's work fine, it just seems like CF is having issues with h5ai.

**Comment by lrsjng** [comment]
@DarkKV I never used CloudFlare, but there were some problems reported in the past using CloudFlare. I never heard that this could be fixed..

**Comment by DarkKV** [comment]
@lrsjng oh well, I guess I'll stick to incapsula for now. Thanks :)

**Comment by lrsjng** [comment]
this might also have caused the difference between installed files and error reports..? Incapsula works better?

**Comment by DarkKV** [comment]
@lrsjng Possibly, I did switch over to cloudflare briefly today... Only to find that it is still in fact broken. Incapsula works perfectly, although their free tier plan has a lot less features than Cloudflare, nethertheless it's still a great CDN.

**Comment by isaumya** [comment]
I've also just now witnessed issue with cloudflare rocketloader and h5ai. Thought I should report it here.
