### ISSUE TITLE
Add login feature

### ISSUE THREAD

**Issue by DanielRamosAcosta** [lrsjng/h5ai#422]
The ability to add users and their own home folder. That would be awesome!

**Comment by lrsjng** [comment]
@DanielRamosAcosta hi Daniel, this will not make it into h5ai at the moment (and most likely not in the long term). You can set up h5ai in subfolders though. So you can use your server's access restriction for user accounts, and set up a separate installation of h5ai in her/his subfolder.

**Comment by DanielRamosAcosta** [comment]
Ok, thanks you!
