### ISSUE TITLE
Move javascript to the bottom

### ISSUE THREAD

**Issue by XhmikosR** [lrsjng/h5ai#425]
Having `script.js` in the header offers no again apart from slowing down page load. You should move it before the `</body>`.

**Comment by lrsjng** [comment]
Doesn't make much sense in this use case, does it?

**Comment by XhmikosR** [comment]
It totally makes sense. Having it in `head` blocks the page rendering until the file is downloaded.

**Comment by lrsjng** [comment]
nothing there to be rendered until the JS kicked in.. (besides fallback)

**Comment by XhmikosR** [comment]
Still, it blocks rendering. Not my words (only), google it and you'll see for yourself.

**Comment by lrsjng** [comment]
I know this articles, and it definitely blocks rendering, but there is nothing to be rendered anyway.. all will kick off on page ready event.

**Comment by XhmikosR** [comment]
Even if that's the use case here, it **certainly** does not hurt to have it at the bottom; it can only help.

**Comment by lrsjng** [comment]
?? ..and it would **certainly** make no sense.. :)

**Comment by XhmikosR** [comment]
Nope, it totally makes sense. You shouldn't have it in `head` in the first hand.

**Comment by lrsjng** [comment]
In this use case it doesn't matter at all where the script is.. please, either bring some solid arguments -for this use case- or close this issue..

**Comment by XhmikosR** [comment]
It's proven it's slower in head. Period. Regardless the use case. So it cannot hurt.

Sure, you can keep believing your choice is better, but it clearly isn't.

**Comment by lrsjng** [comment]
..please, read my comments, never said it's better in any way, it's the same..

**Comment by XhmikosR** [comment]
Sure, the same, so no reason to have it head.

But whatever, my bad for trying to improve the frontend part.

**Comment by lrsjng** [comment]
If it's the same it does not improve the frontend part. After thinking about it again (see that I really try to follow your thoughts) it would even make the frontend part worse. I need to have at least modernizr at the top to not have a fallback-flicker. Hence I would need to split the script file into two files, modernizr top, rest bottom. But that would double the HTTP request for the script part.. what am I missing?
