### ISSUE TITLE
Improve status bar for small screens

### ISSUE THREAD

**Issue by XhmikosR** [lrsjng/h5ai#428]
Currently, status bars interferes with the page content with small screens. It can be improved.

**Comment by lrsjng** [comment]
what status bar?

**Comment by XhmikosR** [comment]
When viewing a txt file, for example.

**Comment by XhmikosR** [comment]
I'd say making the filename and size stack one below the other would be better with less padding and space.

**Comment by lrsjng** [comment]
Ah, I see, I'm planning to crop this infos for small screens, as done with the topbar

**Comment by lrsjng** [comment]
Fixed in 99a45ab56e7166e70f4888b3d05eeeb6a98fa153.
