### ISSUE TITLE
Default icon sizes

### ISSUE THREAD

**Issue by mkskarch** [lrsjng/h5ai#431]
In `options.json` there is an array of icon sizes. The first value shall indicate the default view size, but that does not work in v0.27, regardless of what number I put as the first value, the default view does not change. It worked fine in v0.26, though. 

Besides that, v0.27 is really great! Thanks a lot for your work!

**Comment by lrsjng** [comment]
@mkskarch this works only for first time users, or user with no `localStorage`. Otherwise the browser saves the last chosen options and restores them if the user comes back.
