### ISSUE TITLE
Improvement: jpeg thumbnails 

### ISSUE THREAD

**Issue by mkskarch** [lrsjng/h5ai#433]
If view mode is "icons", the generated thumbnails have always the same orientation (landscape), which is great and looks better, than differently oriented icons.
If the original picture is portrait-oriented, the scripts cut off the lower part of the image, leaving only the top. This looks not good, you only see faces up from the nose. It is possible to cut out a bit from the top and a bit from the bottom, leaving the middle part?

**Comment by mkskarch** [comment]
ok, I could fix this by myself, hopefully this will not affect something, that I can't see at the moment. I modified class-thumb.php (added `$src_y` in the function called thumbs):

        if ($src_r <= $ratio) {
            $src_w = $this->width;
            $src_h = $src_w / $ratio;
            $src_x = 0;
			$src_y = 0.5 * ($this->height - $src_h);
        } else {
            $src_h = $this->height;
            $src_w = $src_h * $ratio;
            $src_x = 0.5 * ($this->width - $src_w);
			$src_y = 0;
        }

        $width = intval($width);
        $height = intval($height);
        $src_x = intval($src_x);
		$src_y = intval($src_y);
        $src_w = intval($src_w);
        $src_h = intval($src_h);

        $this->dest = imagecreatetruecolor($width, $height);
        $icol = imagecolorallocate($this->dest, 255, 255, 255);
        imagefill($this->dest, 0, 0, $icol);
        imagecopyresampled($this->dest, $this->source, 0, 0, $src_x, $src_y, $width, $height, $src_w, $src_h);

**Comment by lrsjng** [comment]
@mkskarch Hi, I've chosen this by design, there will always be missing parts..
