### ISSUE TITLE
Appearance version 27

### ISSUE THREAD

**Issue by Monter** [lrsjng/h5ai#440]
Why version 27 is so ugly compared to version 26? Ugly icons, not hiding a side panel, fuzzy fonts, visually step backwards. There is a some reasonable explanation?

**Comment by lrsjng** [comment]
@Monter I'm just trying different styles to see what I like. As for the font and icons I'm myself not happy with the result. Next release will go back to `Ubuntu` font family and crisp+colored icons. As for the panel thing, I think it's going in the right direction..

**Comment by h404bi** [comment]
As for me, I don't care about the icons, but I don't know why you throw away the flat design, :-[. Maybe you can develop a feature about changing the panel's style not only the icons.

**Comment by lrsjng** [comment]
@h404bi the upcoming release 0.28.0 adds an easy way to add your own stylesheets and scripts to the page, but I don't think there will be any further theme support anytime soon
