### ISSUE TITLE
preview-txt: Support for golang syntax highlight

### ISSUE THREAD

**Issue by jerryjacobs** [lrsjng/h5ai#441]
I added go programming language syntax highlight myself:

conf/types.json: "txt-go" "*.go"
conf/options.json under preview-txt: "txt-go" "go"

It would be nice if you could add this.

**Comment by florianbeer** [comment]
Wouldn't this issue be better suited as a [Pull Reqeust](https://github.com/lrsjng/h5ai/pulls)?

**Comment by jerryjacobs** [comment]
Here you go

**Comment by jerryjacobs** [comment]
This may be closed then :+1:
