### ISSUE TITLE
same with me...no thumbs-no avi preview

### ISSUE THREAD

**Issue by ozett** [lrsjng/h5ai#443]
something to check? no info in apache log ...

**Comment by lrsjng** [comment]
@ozett hi, what is "same with you.."? what's the issue?

**Comment by ozett** [comment]
hmmm i puzzled. did you delete an issue, on which i replied? nevertheless, i have no thumbnails for images, but i dont see any error messages. 
as far as i see, thumbnail-generation is default for images (jpeg) in every folder, but i dont see any thumbnails in my folder-listings. do i need a special debian-package?

another issue (i can/should make another thread?) is, that there is a neverending rotating circle if i click on an avi-file in my folder. images are ok, i see them. but avi-movies (from my webcams) never show up. how do i manage this?

what info should i provide for some help?
many thanks, ozett

**Comment by lrsjng** [comment]
@ozett all green on the info page? as for the video files, h5ai uses the browsers own `<video>` tag, it's completely up to the browser to play the files.. so it depends on your browsers capabilities what will be playable..

**Comment by ozett** [comment]
thanks for the hint. i was a too quick fox...
i read the installation section on your homepage wich says:

"visit http://YOUR-DOMAIN.TLD/_h5ai/. This page shows some hints on the server's capabilities."

but i did not think to check it. because i thougt i got only status-info. 
you could explicity say to check this page, if all packages for all features of h5ai are already installed. just for noobs like me, i think.. 
i will work through it, because somethin is missing

for the avi-preview. i dont get any in none of my three browsers (chrome, ie, firefox, on windows 8)
can i improve this?
![no-avi](https://cloud.githubusercontent.com/assets/5937811/7654307/6b02e702-fb1c-11e4-8899-b5a8535c006b.png)

**Comment by ozett** [comment]
i checked the page and installed:

apt-get install php5-gd imagemagick.

now everthing is green.

it would be helpful it the check-page could tell to normally install package...xy to go from RED to GREEN, i think...

many thanks for helping here...
(still looking forward to avi-preview...)

;-)

**Comment by lrsjng** [comment]
@ozett I think this [page](http://stackoverflow.com/questions/4129674/does-html5-video-playback-support-the-avi-format) might interest you, in particular the bobince's answer.

**Comment by ozett** [comment]
thanks for the link. i see the point.
but i am no coder nor any type of webpage-engineer, but i see youtube is working with videos in browsers. this view on youtube simplifies the coplexitiy of web-techniques, but expresses my hope, that an more experienced person could show a a way to show (at least) a handful of the most common video formats in a browser... maybe a jquery plugin, flash, html5... 
i would be thankful for some hints to test something....

**Comment by lrsjng** [comment]
@ozett it would be working with plugins or flash, but this will not be integrated into h5ai. I don't want to overload it at the moment, I'm sorry..

**Comment by ozett** [comment]
ok. no prob.
but maybe an idee to open up for some kind of (minimal) plugins ?
i found this 
https://github.com/jwplayer/jwplayer
and this
http://www.videojs.com/
as a start to a solution.
but as i am no programmer, i could hardly patch your source, nor would this be a good idea as it would be a temporary solution until next update. a minimal api/interface could be a stable solution for such demands. dont you think so?

now...but as i am a noob, i would extremely thankful for a hint, how to integrate such js.player into h5ai to get videos also in preview...;;--))))))

thaaaaanks,
ozett

**Comment by lrsjng** [comment]
@ozett the next iteration (0.28.0) will have a very *basic* support for user styles and script. It's already in the `develop` branch but not upstream. As with the players I can't help you, I'm sorry..

**Comment by ozett** [comment]
sorry to bother you. topic is clearly discussed.
but....as  far as is it unsatisfactory to click on an avi and have no preview (this is pitiful missing - and your dir-list script is somewhat fantastic) i searched just today the web and found this:

http://www.evoluted.net/thinktank/web-development/php-directory-listing-script

i tried it, and i got my avi's in firefox 38.x and an installed vlc on my laptop to show up. wonderful.
i did not looked into the code, but this wont show up the same way with h5ai...  maybe simple to implement in the development branch? ;-)) i will give it a try...
