### ISSUE TITLE
No files show up.

### ISSUE THREAD

**Issue by n0ided** [lrsjng/h5ai#447]
Hi,

I've installed h5ai under the folder `archive`, and I can browse it and everything, however no files show up. Even if I move an .mp3 or .txt to the `archive` folder and chown it to www-data, there's no error logs either.

How my folder looks:

`cache  client  conf  heh.txt  index.html  README.md  server`

`heh.txt` doesn't show up anywhere. Is this a bug? 

Any help is greatly appreciated :)

Site: http://noided.cf/archive/
http://noided.cf/archive/heh.txt

**Comment by lrsjng** [comment]
@n0ided put folder `_h5ai` into your folder `archive` (the complete folder, not only its content). Then set the DirectoryIndex for `archive` to `/archive/_h5ai/server/php/index.php` in your webserver conf.

**Comment by n0ided** [comment]
@lrsjng Thanks! Do you have any idea how many files one can host without it being laggy?

**Comment by lrsjng** [comment]
@n0ided no, sry, I think it depends a lot on the used browser and server..
