### ISSUE TITLE
Works best with JavaScript enabled! error

### ISSUE THREAD

**Issue by gfxmedia** [lrsjng/h5ai#448]
Hi!
I have problem, my provider change server software from apache to litespeed and h5ai stopped. 

My page: http://test.gfxmedia.pl
h5ai location : http://test.gfxmedia.pl/_h5ai

Someone know how fix it? :(

// sorry for my English :)

**Comment by lrsjng** [comment]
@gfxmedia litespeed is not supported, I'm sorry. Never worked with it..

**Comment by gfxmedia** [comment]
@lrsjng thanks :(

**Comment by gfxmedia** [comment]
@lrsjng I'm add define("APP_HREF", "/_h5ai/"); in /_h5ai/server/php/index.php and it works! :)

works here: http://prace.gfxmedia.pl/

**Comment by lrsjng** [comment]
@gfxmedia that's good, but no guarantees that it works as expected :) I will close this issue here..

**Comment by m1s3rys1gn4l** [comment]
> @lrsjng I'm add define("APP_HREF", "/_h5ai/"); in /_h5ai/server/php/index.php and it works! :)
> 
> works here: http://prace.gfxmedia.pl/

i would like to know  which file you edited ?

**Comment by GGORG0** [comment]
@m1s3rys1gn4l me too. I have the same problem over at https://ggorg.tk

**Comment by GGORG0** [comment]
Ok I found the solution in https://github.com/lrsjng/h5ai/issues/209#issuecomment-839602324_
