### ISSUE TITLE
So i managed to install h5ai correctly i think but not files shows up.

### ISSUE THREAD

**Issue by wazerstar** [lrsjng/h5ai#449]
So the files are installed in the correct sub folder i want it to be in and not in the root of the entire webserver.

I then checked the index.html file and it gave me all greens and goods to go i copied the thing it wanted me to copy and i added it to a new text document, saved it as .htaccess, uploaded it to the folder

DirectoryIndex index.html index.php /demos/server/php/index.php

now h5ai is listed in the sub folders with everything working except the actually files i want to be shown?

Here's the green index.html file status in a picture. This file is of course changed to something random.

http://prntscr.com/79397n

**Comment by lrsjng** [comment]
@wazerstar put the whole folder `_h5ai` into your demos folder (not only its content) then in `demos/.htaccess` add `DirectoryIndex index.html index.php /demos/_h5ai/server/php/index.php`. All folders in `demos` including `demos` itself will be styled by h5ai if they do not contain custom index file.

**Comment by wazerstar** [comment]
@lrsjng Thanks worked!.
