### ISSUE TITLE
Empty folder

### ISSUE THREAD

**Issue by magic282** [lrsjng/h5ai#451]
I have created a new VPS and setup a new site. After I install the h5ai from [here](http://larsjung.de/h5ai/), it can just show `empty`. 

I am using ubuntu 14.04 64bit server and nginx. I have googled some issues here but none of them solved my issue.

**Comment by lrsjng** [comment]
@magic282 did you follow the install instructions? all green on the info page? anything in the PHP error logs? most likely a configuration error, I think..
