### ISSUE TITLE
Works best with JavaScript enabled!Works best in modern browsers!powered by h5ai

### ISSUE THREAD

**Issue by hatim-haffane** [lrsjng/h5ai#452]
i just intalled the h5ai on my ubuntu server 12.04 , i use apache2 , i changed the directory index to : 
DirectoryIndex  index.html  index.php  /_h5ai/server/php/index.php

but i get this error , i have javascript enabled .

any help please

**Comment by lrsjng** [comment]
@hatim-haffane anything in the PHP error log? on Ubuntu you might need to install an extra package for PHP JSON support..

**Comment by hatim-haffane** [comment]
thanks it's working now i dont know what was the problem . i just removed the index.html from apache root directory and its works.

i have an other question : is there any solution to secure h5ai with a password ?

thanks

**Comment by lrsjng** [comment]
No, not via h5ai itself.

From the homepage:

> Please note that h5ai does not work with aliased folders in general (as available in Apache httpd). Aliased folders make it impossible to map URLs to file system folders. Actually any web server specific things aren't supported. That includes access restrictions! Best chance to make restricted areas work and secure might be to place folder _h5ai completely inside that resticted area. Use it at your own risk.
