### ISSUE TITLE
Files larger than 2GB on 32-bit compiled PHP

### ISSUE THREAD

**Issue by cybtachyon** [lrsjng/h5ai#456]
Calculated file sizes will hang on files >2GB on 32-bit compiled php.

See http://stackoverflow.com/questions/17114827/php-fseek-for-large-file-2gb

It might be worth it to implement the solution in http://stackoverflow.com/questions/5501451/php-x86-how-to-get-filesize-of-2gb-file-without-external-program - let me know what you think. If it sounds good I can try to hack away on it if I get the time.

**Comment by lrsjng** [comment]
@cybtachyon I removed all workarounds for 32bit PHP in the last release (0.29.0). Starting with PHP 7 there are 64bit version for Windows now. So everyone concerned about large files and file sizes will be able to set up a appropriate server environment.
