### ISSUE TITLE
blank white  page with no listing

### ISSUE THREAD

**Issue by mbassiouny33** [lrsjng/h5ai#462]
Hi, I've installed the latest version of h5ai (0.27.0) and I got a blank page with no listing inside it, I wish to know what can possibly cause this problem so I can fix it.
I've edited the .htaccess file of this folder http://goo.gl/5lu2PM
but still I get a blank page.
I'm using apahe 2.4.6 on a centos server
I'm waiting for help, and thanks in advance

**Comment by frozeus** [comment]
Read the installation section here : https://larsjung.de/h5ai/

**Comment by mbassiouny33** [comment]
thanks, but I don't need a link to the manual after 1 month :-1:  . 
I have already solved my issue, and it wasn't covered in the installation section, btw. 
My issue was a conflict by the sentora panel that I've installed on the same server.
Apparently sentora isn't compatible with h5ai.
