### ISSUE TITLE
How to read ID3 Tag of mp3

### ISSUE THREAD

**Issue by efuzone** [lrsjng/h5ai#463]
Hello,

My files name are 1.mp3 2.mp3 but in file tags there are title etc all so how to make this script read tital tag and show file name as title tag?

**Comment by frozeus** [comment]
h5ai display the real name of a file if you want to show the id3tag just rename it.

http://eyed3.nicfit.net/

**Comment by lrsjng** [comment]
@efuzone features like that won't make it into h5ai in the near future, I'm sorry.
