### ISSUE TITLE
File upload stopped working after upgrade from 0.25

### ISSUE THREAD

**Issue by agilob** [lrsjng/h5ai#465]
Can't find any option to re-enable it, doesn't work with any browser, nginx and php-fpm config is the same.

**Comment by frozeus** [comment]
Server side file manipulation has been removed : https://github.com/lrsjng/h5ai/issues/292

I made a fork to keep these features enabled but it's unsecure, unstable and not up to date.
https://github.com/frozeus/h5ai

**Comment by agilob** [comment]
so basically it's just a file browser now? :<

**Comment by frozeus** [comment]
"h5ai was never planned to be a file manager. The initial idea was to have a pleasant file index"
But it might be possible to create extensions on server/client to allow these file manipulations on 0.27.
