### ISSUE TITLE
Using h5ai's zip archiver, file name crashes

### ISSUE THREAD

**Issue by hsk22000** [lrsjng/h5ai#466]
Well, title equals what I'm saying;

My server uses UTF-8 Encoding which you said h5ai supports well.
then, When I use archiver(multiple file to single .tar file)
file name crashes like this;

윤하-14.혜성.mp3
?ㅽ븯-?쒖꽦.mp3

any method to fix this? I had tried to add or update encoding(s) to my server but still not fixed.

**Comment by lrsjng** [comment]
@hsk22000 could you please check if this is still an issue with one of the latest [dev builds](https://release.larsjung.de/h5ai/develop/)?

**Comment by hsk22000** [comment]
OK, I'll check this now.

**Comment by hsk22000** [comment]
I can't find any checkbox to make multiple choice.

where is it?

**Comment by lrsjng** [comment]
to use the download extension you need to enable the [download extension](https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/private/conf/options.json#L125) and the for selective download the [select extension](https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/private/conf/options.json#L321).

My testing folder is the [special chars](https://larsjung.de/h5ai/demo/special%20chars/) folder of the demo, if you wnat to have a look.

And, v0.29.0 is out now.

**Comment by hsk22000** [comment]
Ahh, okay. I'll re-upload latest bulid.

**Comment by hsk22000** [comment]
See this screenshot [https://nas.hsk222.kr/index.php/s/Q4wisAB5KAzy7yV](url)

same file, and now filename not crashes.

I updated my server(well, completely did clean-install few days ago) before got this change.

**Comment by lrsjng** [comment]
@hsk22000 so everything is working fine now?

**Comment by hsk22000** [comment]
@lrsjng Yes, maybe.

I think it is not the h5ai's problem but the zipper(sry, I forgot name) package's problem.

**Comment by lrsjng** [comment]
@hsk22000 fine, enjoy :+1:

**Comment by hsk22000** [comment]
[https://nas.hsk222.kr/index.php/s/Hl7OWxKOfgt3qRW](url)

I tested some more files contains korean, english, japanese.

still fine.
