### ISSUE TITLE
Multiple selection start position is relative to the screen, should be relative to page.

### ISSUE THREAD

**Issue by jesskay** [lrsjng/h5ai#468]
When selecting more than one screen of files, moving to the edge scrolls the page, but the selection's start (top if selecting downwards, bottom if upwards) remains in the same place on the screen, causing it to deselect the files above as you scroll down. The start position should be relative to the page instead so that more than one screen of files can be selected.

(Also recorded a demonstration if the problem was hard to understand from my description: https://dl.dropboxusercontent.com/u/86596534/1507/2015-07-24_00-40-50.webm)

**Comment by lrsjng** [comment]
fixed in the latest [dev builds](https://release.larsjung.de/h5ai/develop/)
