### ISSUE TITLE
File name Encode Bug In non-English file name

### ISSUE THREAD

**Issue by LiJinyao** [lrsjng/h5ai#477]
Hello,
I put a file with Chinese name and the  name shows like url:
![2015-10-12_213728](https://cloud.githubusercontent.com/assets/3450595/10429219/b1a20340-7129-11e5-8d51-818bf94fc13d.png)
The right File name is:
![2015-10-12_214004](https://cloud.githubusercontent.com/assets/3450595/10429258/d634fd20-7129-11e5-84b2-ff78338cf7c7.png)

Here's the Chinese file name: 测试 for test.

Thank you in advance.

**Comment by Scrxtchy** [comment]
I have a few files on my storage unit that have folder/filenames that I suggest where entered using a Shift_JIS set (More commonly known as a japanese encoding)
This returns an issue similar to that you have posted
![](https://jii.moe/EyLWCKmX-.png)

However, there are a lot of cases where this is not the case, and foreign characters render normally
![](https://jii.moe/EkPzRtm7W.png)

By default, my pages are returned with a UTF-8 (Unicode) encoding, which asks the question as to what the filenames have been encoded with

**Comment by lrsjng** [comment]
@LiJinyao @Scrxtchy  recently added a [special chars](https://larsjung.de/h5ai/demo/special%20chars/) folder to the demo (all files empty), seems to work okay.. can you tell something more about the environment you're using: OS, server, browser, h5ai, file system, versions?

**Comment by Scrxtchy** [comment]
Are your filesnames encoded with a well known encoder?
throwing ```%83q%83Q%83h%83%89%83C%83o%81%5B2UP%20%282009%29``` into a decoder with the source fomatting of S_JIS and displayed as GB2312 or UTF-8, and a postfilter of urlencoded or x-esc-entities, I was able to recode it as viewable characters
![](http://jesusfuck.me/di/ZSEK/16-08-12-21-15-41-universal-online-cyrillic-decoder-recover-your-t.png)

As for specifics, the server runs Nginx on Gentoo with a xfs type filesystem.
Browser using Mozilla 47.0.1
h5ai version 0.28.1

**Comment by lrsjng** [comment]
@Scrxtchy just used [google translate](https://translate.google.com/) to get some characters/letters in different languages..

here's what it looks like for me:

![screenshot from 2016-08-12 13-28-27](https://cloud.githubusercontent.com/assets/181815/17621030/e9f1d8c2-6090-11e6-8692-72309df3aa08.png)
