### ISSUE TITLE
Not calc the size of folders when are Polish letters

### ISSUE THREAD

**Issue by Olafejs** [lrsjng/h5ai#480]
Not calc the size of folders when are Polish letters ex.

![11111](https://cloud.githubusercontent.com/assets/11058593/10756767/b0a31208-7ca6-11e5-9bda-c542f4ade151.PNG)

**Comment by lrsjng** [comment]
@Olafejs recently added a [special chars](https://larsjung.de/h5ai/demo/special%20chars/) folder to the demo (all files empty), seems to work okay.. can you tell something more about the environment you're using: OS, server, browser, h5ai, file system, versions?
