### ISSUE TITLE
Tag recent Version

### ISSUE THREAD

**Issue by dennisausbremen** [lrsjng/h5ai#483]
Is it possible to tag the newest Version of this repo or is the current state more like "develop"?

**Comment by lrsjng** [comment]
@dennisausbremen all releases are tagged, latest release is tagged `v0.27.0`

**Comment by dennisausbremen** [comment]
@lrsjng I was just wondering, because MASTER ist more recent than the latest release and why there is no release `v0.27.x` for the most recent codebase.
