### ISSUE TITLE
Use with Dreamhost DreamOjbects CDN buckets?

### ISSUE THREAD

**Issue by dlewand691** [lrsjng/h5ai#484]
Have uploaded and configured accordingly and am only getting an XML layout of the contents, not the "pretty" UI as expected. Is this compatible with CDNs? Also has a reference link listed to <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">

See here: http://randassets.objects.cdn.dream.io/

**Comment by SushiDude** [comment]
DreamSpeed is based on Fastly which uses Amazon S3. Considering how S3 only serves files, and does not execute PHP, it appears that the CDN is misconfigured. This is not an issue with H5AI.
