### ISSUE TITLE
Sound only working on some video

### ISSUE THREAD

**Issue by phxn** [lrsjng/h5ai#486]
Is there a fix required to get audio working on the video preview mode? Only some audio works, whilst some are muted.

I've been using this on my server and it's extremely fast, playback begins instantly and seeking is also instant. If I could get a solution for the sound problems this would act very nicely as a media center.

**Comment by tap3** [comment]
same issue

**Comment by furest** [comment]
Hi guys!
It's "normal" to have audio not working on some videos as the HTML5 video player doesn't support DTS, AAC and AC3 audio codecs. Try converting the video to a different format (mainly for the audio) and it will work.

**Comment by sshuangliu** [comment]
> Hi guys! It's "normal" to have audio not working on some videos as the HTML5 video player doesn't support DTS, AAC and AC3 audio codecs. Try converting the video to a different format (mainly for the audio) and it will work.

maybe can follow this guide to convent file ,hope userful for someone else

https://gist.github.com/jamesmacwhite/58aebfe4a82bb8d645a797a1ba975132
