### ISSUE TITLE
Disable Menu Button?

### ISSUE THREAD

**Issue by phxn** [lrsjng/h5ai#487]
Is there any way to disable the menu button on the top left? (The one that leads to Tree/Language/Info settings).

Even when disabling everything, the icon remains and opens up a narrow pane with nothing inside.

It would be nice if we could disable/hide this button completely.

**Comment by lrsjng** [comment]
implemented in the latest [dev builds](https://release.larsjung.de/h5ai/develop)

new option: `view -> disableSidebar`
