### ISSUE TITLE
RFE: Support for NGINX json autoindex (alternative backend)

### ISSUE THREAD

**Issue by xor-gate** [lrsjng/h5ai#488]
Since nginx version 1.7.9 it supports `autoindex_format json; directive`. When the directive is on, nginx produces very lightweight autoindex in JSON format. . I'm also willing to give a bounty of 10 euro to integrate this (have no clue it is more work than that amount).

See (reference javascript implementation):
https://github.com/kstep/nginx-autoindex-js

NGINX autoindex module:
http://nginx.org/en/docs/http/ngx_http_autoindex_module.html

**Comment by lrsjng** [comment]
h5ai will not add any server specific things.. I'm sorry

**Comment by xor-gate** [comment]
Yeah I understand, but h5ai is very very nice and currently it needs PHP to run on the server side. As i have tried to create a Golang HTTP server to emit h5ai-ish indexing. If I remember correctly there is no real protocol/specification how PHP interacts with the browser so h5ai is very-tight integrated with current PHP reference implementation.
