### ISSUE TITLE
How to access info page

### ISSUE THREAD

**Issue by XhmikosR** [lrsjng/h5ai#490]
Hi.

I updated to v0.28.1 and I can't figure out how to access h5ai's info page anymore. With 0.27, the info was available in `/_h5ai/`.

Thanks.

**Comment by lrsjng** [comment]
Installation process changed in version 0.28.0

```
Copy folder _h5ai to the document root directory of the web server: DOC_ROOT/_h5ai.

DOC_ROOT
 ├─ _h5ai
 ├─ your files
 └─ and folders

Visit http://YOUR-DOMAIN.TLD/_h5ai/public/index.php, this page shows some hints on the server's capabilities.

Add /_h5ai/public/index.php (note the leading slash!) to the end of the default index-file list. In this way h5ai will manage all directories in and below DOC_ROOT that don't have a valid index file.
```

**Comment by XhmikosR** [comment]
I have already done that; the frontend works fine but I can't access the info page by doing `/_h5ai/`.
It must be a permissions issue because I'm seeing 403. Can it be because the the cache folders don't have the view permission?

**Comment by XhmikosR** [comment]
Sorry for the noise, I'll try to figure out the permissions later.

**Comment by lrsjng** [comment]
as said above it's not at `/_h5ai/` any longer, you have to point your browser to `/_h5ai/public/index.php`...

**Comment by XhmikosR** [comment]
You are right, thanks. Can this be documented?

On a side note, in one of my servers I can see the folders when I do `/_h5ai/`. I need to reconfigure the permissions.

**Comment by lrsjng** [comment]
my first answer is a copy of the installation instructions on the project page..

**Comment by XhmikosR** [comment]
You are right, I missed it.

So, now the only issue I have is _h5ai/public and _h5ai/private being browseable although their contents are hidden.  `https://nightly.mpc-hc.org/_h5ai/`

**Comment by XhmikosR** [comment]
I'm also getting
```
14:29:22.467 syntax error Info.md:1:1
```

when trying to view Info.md but it appears to show up fine.

**Comment by Joery** [comment]
Does your web server support .htaccess files? There are .htaccess files in both public & private folders which should direct users to a 403.

**Comment by XhmikosR** [comment]
Yeah, it does. But for some reason I can access those folders even if they are shown as empty. So, I reverted to 0.27 for the time being.
