### ISSUE TITLE
Does it work on PHP 7.0.1?

### ISSUE THREAD

**Issue by doio** [lrsjng/h5ai#494]
Everything works fine without adding the line
DirectoryIndex  index.html  index.php  /_h5ai/public/index.php
to .htaccess  in ROOT, apache starts then stops and restarts, there's no error info on error.log in Apache and I have to stop using _h5ai for my website to work.

Have been using the same config for PHP 7.0.0 and below and 7.0.0 used to work and all a sudden _h5ai stopped working somehow....

**Comment by Adwelean** [comment]
I have the same problem with xampp and php 7.0.1.

**Comment by lrsjng** [comment]
works fine for me with 7.0.1

I used the following PHP build commands are
```
> ./configure --prefix=/some/install/folder --enable-cgi --with-gd --with-jpeg-dir=/usr/lib --with-png-dir=/usr/lib --enable-exif
> make
> make test
> make install
```

**Comment by lrsjng** [comment]
anything in the error logs?

**Comment by Adwelean** [comment]
I have edited my previous comment :-)

**Comment by lrsjng** [comment]
@Adwelean the PHP error.log would be more interesting

**Comment by Adwelean** [comment]
Okay I think I am stupid but is now work after many many restarts, 
xampp cache ? or something like that ? I don't now :x but it solved for me thanks @lrsjng

**Comment by infectormp** [comment]
work fine on PHP 7.0.4 @ gentoo
