### ISSUE TITLE
hideFolders boonlean doesn't work for folder tree

### ISSUE THREAD

**Issue by Joery** [lrsjng/h5ai#496]
When the boonlean value "hideFolders" is enabled, the folders are hidden in the main overview but not in the folder tree.

Am I missing an option or is this a bug?

Thank you.

Screenshot example.
http://i.imgur.com/lBGFVXp.png

**Comment by Joery** [comment]
Next to this I want to add when hideFolders is enabled, the contents in folders can still be seen when you use the search function.

Maybe a option to disable search in underlying folders. (So it only searches in the current folder?)

**Comment by lrsjng** [comment]
@Joery `hideFolders` affects only the main view. Doesn't make much sense for the tree sidebar, as the tree only shows folders, and then there would be nothing to show. But you can disable the tree completely if you want that.
