### ISSUE TITLE
Separate storage from code

### ISSUE THREAD

**Issue by postblue** [lrsjng/h5ai#498]
I'm using h5ai with NGinx (1.8.0) and PHP5-FPM (PHP 5.6.17-0+deb8u1) on Debian Jessie. It does an amazing job. But here I'm trying to rework my server architecture and I would like to separate storage and code. For instance, not having `_h5ai` folder in the directory if opened in a file manager, but used/displayed in a web browser.

But is it possible? If it is, how? I'm a little bit stranded with this.

Here's my NGinx configuration:

```
server {
        listen 80;
        root /var/www/h5ai;
        server_name h5ai.domain.tld;

        location / {
                index /_h5ai/public/index.php;
                try_files $uri $uri/ /_h5ai/public/index.php;
                autoindex on;

                location /_h5ai/private {
                        deny all;
                        return 403;
                }

                location ~ \.php$ {
                        include snippets/fastcgi-php.conf;
                        fastcgi_pass unix:/var/run/php5-fpm.sock;
                }
        }
}
```

**Comment by lrsjng** [comment]
@postblue currently that is not possible since the location of folder `_h5ai` marks the root folder. but as a workaround it should work if you rename folder `_h5ai` and all its references in your nginx conf to `.h5ai` so that the folder at least is hidden in your file manager..

**Comment by clangcn** [comment]
View page source will be exposed
