### ISSUE TITLE
PHP 5.5 requirement

### ISSUE THREAD

**Issue by Maxime-J** [lrsjng/h5ai#501]
Hi,

I currently run 0.28.1 version with php 5.4 for a personal sharing service and I didn't see any problem.
So could you tell me what is the code that justifies the 5.5 MIN_PHP_VERSION?

Thanks,

**Comment by lrsjng** [comment]
There is none, it might even work with 5.3. But support for 5.4 ended (last summer, I think) and so I stopped testing/supporting it. You should consider an update, since you won't get security updates for 5.4.

**Comment by Maxime-J** [comment]
Thank you for the quick answer.
Yes, support ended but RedHat still doesn't officialy provide and maintain php > 5.4 for their OpenShift Online hosting.

**Comment by mckaygerhard** [comment]
the software does not run with php 5.3, i must backported all array realted, due php 5.4 now can declare arrays as with simple corchets

php 5.3:

arre = array();

php 5.4+/php5.5+

arre = [];

so then i backported and works fine now withphp 5.3..

so this issue are not resolved! u must change around 112 lines and then works in any installation

i personally noted php 5.3 are more faster rather thant 5.5 and 5.4.. i run a webserver with 300/600 resquest concurenty in a hour at day in my job, optimizations and performance are important
