### ISSUE TITLE
Apache 2.4 - .htaccess files are incompatible

### ISSUE THREAD

**Issue by ddarbyson** [lrsjng/h5ai#504]
The following files are incompatible with Apache 2.4 directives.

https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/.htaccess
https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/private/.htaccess
https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/public/.htaccess

You should be using the respective denied, and granted accordingly if you wish maintain compatibility with Apache 2.4:

**Deny**

```apache
# Apache < 2.3
<IfModule !mod_authz_core.c>
  Satisfy all
  Order deny,allow
  Deny from all
</IfModule>

# Apache ≥ 2.3
<IfModule mod_authz_core.c>
  Require all denied
</IfModule>
```

**Allow**

```apache
# Apache < 2.3
<IfModule !mod_authz_core.c>
  Satisfy all
  Order allow,deny
  Allow from all
</IfModule>

# Apache ≥ 2.3
<IfModule mod_authz_core.c>
  Require all granted
</IfModule>
```

**Comment by lrsjng** [comment]
@ddarbyson works fine on my local server (2.4.4). should be no problem due to `mod_access_compat.c`

**Comment by ddarbyson** [comment]
@lrsjng or you can use the deprecated module. Thanks for the tip!

**Comment by mckaygerhard** [comment]
these files are unuseless, htaccess files only works for apache threats

mayor huge of vendors use apache cgi (and fpm, rest of servers uses php-cgi and fpm), 
**apache fpm, apache cgi, and rest of servers ignores htaccess files** so the proper way to use its with user.ini files and php specific settings in webserver made in instructions install

htaccess files are poinless and unuseless
