### ISSUE TITLE
Empty subfolders

### ISSUE THREAD

**Issue by metuskale** [lrsjng/h5ai#505]
After installing in a directory in another partition I can see all files in root folder but as soon as I go into a subfolder it shows as empty.

**Comment by rez0n** [comment]
Hello! Have some case and fix this problem.
Are you have httpd 2.2 ?
1. Add to root .htaccess file - `DirectoryIndex index.html index.php /cfg/_h5ai/public/index.php`
2. Comment in _h5ai/.htaccess last line `#Require all granted`

If this not help - lets check your error.log
