### ISSUE TITLE
filter/search is case sensitive

### ISSUE THREAD

**Issue by cka3o4h1k** [lrsjng/h5ai#508]
I google issues, and problem with search seems to be resolved
But today I start useng h5ai on Centos7/php7/nginx and search case sensetive

I add "ignorecase" - without result

   "search": {
        "enabled": true,
        "advanced": true,
        "debounceTime": 300,
	"ignorecase": true
    },

How possible to make search insensetive?

**Comment by lrsjng** [comment]
fixed the latest [dev builds](https://release.larsjung.de/h5ai/develop)
