### ISSUE TITLE
Use password function from info.php

### ISSUE THREAD

**Issue by 20Fourteen** [lrsjng/h5ai#514]
Hi,

I would like to use the password function from the info page to lock down the root folders, please let me know if and how this can be done.

This is just to keep curious eyes out.

Many thanks

**Comment by 20Fourteen** [comment]
Any thoughts about this issue?

**Comment by georgesuba** [comment]
Hi, for protection you can use htaccess.. I did mine for multiple users with one htpasswd.

**Comment by 20Fourteen** [comment]
I know and can use it, but I'm looking for a more elegant solution.

**Comment by RomeSilvanus** [comment]
I'm not a developer, but seeing as this function already wors on the info page shouldn't it be relatively easy to implement ?

Would be a nice option for some private installations.

**Comment by georgesuba** [comment]
@RomeSilvanus you can have folders hidden on apache.. @20Fourteen well you can still code it in if apache htpasswd is not good for you..

**Comment by lrsjng** [comment]
This is not supported, I'm sorry. It's not planned to add auth/access restrictions in the future.
