### ISSUE TITLE
Package download fails if the file name has special characters

### ISSUE THREAD

**Issue by DevSplash** [lrsjng/h5ai#516]
If a file name has special characters,report error when I download it as package (zip or tar).
I modified the code as this url:`https://github.com/lrsjng/h5ai/issues/140`
But it doesn't help.

For example:
directory structure:

> DOC_ROOT
>  ├─ _h5ai
>  ├─ file1.jpg
>  ├─ file2.jpg
>  └─ ß[].jpg

If I download "ノ.jpg" as package,the package will contains "file1.jpg" and "file2.jpg",but "ノ.jpg" isn't in the package.
If I download "ノ.jpg" and "file1.jpg" as package,the package will only contains "file1.jpg".

How can I solve this problem?

**Comment by BlueSplash** [comment]
This problem seems to be caused by "escapeshellarg",but I don't know how to deal with it.
So I modified "_h5ai/private/php/ext/class-archive.php":
```
    private function shell_cmd($cmd) {
        $cmd = str_replace('[ROOTDIR]', urldecode(escapeshellarg(urlencode($this->base_path))), $cmd);
        $cmd = str_replace('[DIRS]', count($this->dirs) ? implode(' ', array_map('urldecode',array_map('escapeshellarg', array_map('urlencode',$this->dirs)))) : '', $cmd);
        $cmd = str_replace('[FILES]', count($this->files) ? implode(' ', array_map('urldecode',array_map('escapeshellarg', array_map('urlencode',$this->files)))) : '', $cmd);
        try {
            Util::passthru_cmd($cmd);
        } catch (Exeption $err) {
            return false;
        }
        return true;
    }
```
This is not the best way,do you have a better solution?

**Comment by lrsjng** [comment]
works fine for me, no problems with special characters in display and download.. should work in general with uft-8 encoding..
what file-system encoding are you using?

**Comment by BlueSplash** [comment]
I use UTF-8 encoding.

**Comment by lrsjng** [comment]
@BlueSplash recently added a [special chars](https://larsjung.de/h5ai/demo/special%20chars/) folder to the demo (all files empty). Could you please check if packaged download works from your end too?

**Comment by BlueSplash** [comment]
This problem still exists in 0.29.0.

**Comment by lrsjng** [comment]
@BlueSplash do you mean the [demo](https://larsjung.de/h5ai/demo/special%20chars/) doesn't work for you, or your setup does not work?

**Comment by lrsjng** [comment]
@BlueSplash just added your proposed file name `ノ.txt` to the demo, works fine too

**Comment by BlueSplash** [comment]
The problem recurs when bulk downloads.

**Comment by lrsjng** [comment]
@BlueSplash in the demo? or in your setup?

**Comment by BlueSplash** [comment]
demo

**Comment by lrsjng** [comment]
what OS and browser are you using and what package viewer (+version)?

**Comment by lrsjng** [comment]
can you post a screenshot?

**Comment by BlueSplash** [comment]
Ubuntu 15.04
Linux version 2.6.32-042stab112.15

I found that my system encoding is POSIX.What's this..

**Comment by lrsjng** [comment]
POSIX is not an encoding.. just google it

what browser are you using and what package viewer (+version)? can you please post a screenshot of the problem?

**Comment by BlueSplash** [comment]
server?

**Comment by lrsjng** [comment]
* please post a screenshot that shows the content of a bulk downloaded package from the demo page, to see what we are talking about
* and please tell me the browser and browser-version you are using
* and please tell me the package viewer you are using

**Comment by BlueSplash** [comment]
![00](https://cloud.githubusercontent.com/assets/15691402/17649368/9426493c-6266-11e6-8c13-74dad260d086.png)
![01](https://cloud.githubusercontent.com/assets/15691402/17649367/94055204-6266-11e6-879d-bf850a15cca7.png)
It can be download from the demo,but files' name are wrong.

Firefox 48.0,Winrar5.31,

**Comment by BlueSplash** [comment]
And in my server,it can't be download.Special characters file not in the package.

**Comment by lrsjng** [comment]
thank you!

can you please try to open the package from the demo page with [7-zip](http://www.7-zip.org/) and/or send me the tar-file?

**Comment by BlueSplash** [comment]
7-zip is ok,but show error.(In fact there is no problem)
![02](https://cloud.githubusercontent.com/assets/15691402/17649463/a1845f7c-6268-11e6-8a76-5d0834ab4048.png)

Tar can't be upload,so I package it as zip.
[special chars.zip](https://github.com/lrsjng/h5ai/files/417039/special.chars.zip)

**Comment by lrsjng** [comment]
the content of the package you sent me is fine, all names correct.. so I think it's a problem with wintar

**Comment by BlueSplash** [comment]
But it still can't package in my server.How to solve this problem?

**Comment by lrsjng** [comment]
You need to get your file encoding to use UTF-8. When uploading files to the server ensure that they are handled as UTF-8..

**Comment by lrsjng** [comment]
this is what helped other users with the similar problems:
* #466 
* #477 
* #567

**Comment by BlueSplash** [comment]
OK...thanks
