### ISSUE TITLE
h5ai on subdomain HTTPS

### ISSUE THREAD

**Issue by bilyboy785** [lrsjng/h5ai#517]
Hi, i configure h5ai and it's works with mydomain.com/dl/, but when i ask dl.mydomain.com, it's the basic index of apache. How can i configure this with my subdomain in https ?

**Comment by georgesuba** [comment]
Hi, server with ssl is possible with htaccess.. regards the question on subdomain, you just create subserver (subdomain) and in public_html you place same setup as in /dl folder.. I can confirm that its working without issue. If you use some hosting company then you need to talk to them..
