### ISSUE TITLE
Don't display JS/Modern Browser warning on Text-Only Browsers

### ISSUE THREAD

**Issue by MechMK1** [lrsjng/h5ai#521]
It would be a nice feature to check for command-line browsers and tools as user-agents (libcurl, Lynx, etc.) and not display a warning for them to enable JavaScript.

**Comment by lrsjng** [comment]
Added in the latest [dev builds](https://release.larsjung.de/h5ai/develop/) starting with `0.28.1+031~aa87ec1`. Checks user agent for `curl`, `links`, `lynx` and `w3m`. Would be cool if you could check if this works for you
