### ISSUE TITLE
Too much data on per thumb request

### ISSUE THREAD

**Issue by cygmris** [lrsjng/h5ai#525]
I wonder why it post a lot of data on per post to get the thumb of our resources instead of post the directory path and indicate some get-thumb flag etc.

This may help saving uncountable server side work.

**Comment by imluckie** [comment]
Heya, could you tell me how did you enable the thumbnail view ?
I'm on ver 0.28.1.

**Comment by cygmris** [comment]
You means the image thumbnail or the video one?
Image thumbnail would be working properly after you have php with EXIF and GD extension enabled.
But speaking to the video thumbnail, if you are in Windows environment, you can follow the instruction in my [pr-526](https://github.com/lrsjng/h5ai/pull/526) to make it works.

**Comment by lrsjng** [comment]
Each image triggers two API requests (bundled with others into a single HTTP request), one for a square thumb and one for a landscape thumb, each with path and dimensions, that's all. Actually all this data reduces server side work.
