### ISSUE TITLE
SVG previews no longer showing after upgrading to 0.28.1

### ISSUE THREAD

**Issue by dlewand691** [lrsjng/h5ai#527]
Upgraded to 0.28.1 and SVG files are no longer previewing. How can I add that option back? Worked fine in 0.27.

**Comment by lrsjng** [comment]
The latest [dev-builds](https://release.larsjung.de/h5ai/develop) now use `img-svg` instead of `txt-svg`. That enables image preview for `*.svg` files (but no thumbs supported).
