### ISSUE TITLE
Stuck at login page

### ISSUE THREAD

**Issue by Phatslam** [lrsjng/h5ai#532]
I'm trying to set this up on FreeBSD and I'm unable to login.  Regardless of what I put in the password field, pressing the login button seems to do nothing but refresh the login page.  It does not generate an error in the browser, and I can't find an error in the Apache logs.  Do I need to increase the Apache log level or activate some other logging in order to track down the problem?

**Comment by kuoruan** [comment]
I have the same problem. maybe it is caused by the permission.

**Comment by kuoruan** [comment]
I just solved the problem, php-fpm user must have write access to `php_value[session.save_path]` in php-fpm config file. eg: /var/lib/php/session
