### ISSUE TITLE
"Input variables exceeded 1000"

### ISSUE THREAD

**Issue by mozai** [lrsjng/h5ai#535]
I have a directory of 300 images.  not all the thumbnails are generated; some appear, but then I see these error messages:

PHP Warning:  Unknown: Input variables exceeded 2047. To increase the limit change max_input_vars in php.ini. in Unknown on line 0
PHP Notice:  Undefined index: width in .../private/php/core/class-context.php on line 259
PHP Notice:  Undefined index: height in .../private/php/core/class-context.php on line 259
PHP Warning:  Division by zero in .../private/php/ext/class-thumb.php on line 211
PHP Warning:  imagecreatetruecolor(): Invalid image dimensions in .../private/php/ext/class-thumb.php on line 229
PHP Warning:  imagecolorallocate() expects parameter 1 to be resource, boolean given in .../private/php/ext/class-thumb.php on line 230
PHP Warning:  imagefill() expects parameter 1 to be resource, boolean given in .../private/php/ext/class-thumb.php on line 231
PHP Warning:  imagecopyresampled() expects parameter 1 to be resource, boolean given in .../private/php/ext/class-thumb.php on line 232

I tried upping the max_input_vars in php.ini, and that gets me more thumbnails, but even at 2048 max_input_vars it's not enough for all three hundred images in the directory.  Yikes.

**Comment by RomeSilvanus** [comment]
Maybe this is relevant to you: 
https://github.com/lrsjng/h5ai/issues/506#issuecomment-192798926
https://github.com/lrsjng/h5ai/issues/506#issuecomment-208308453

**Comment by mozai** [comment]
yeah, looks like it's relevant. PHP default settings breaking on just 250 files, and "just throw more resources at the problem" is an unsatisfactory solution.

**Comment by lrsjng** [comment]
this should be fixed in the latest [dev builds](https://release.larsjung.de/h5ai/develop/). Actually it should be fixed in two ways:

1. API request are now single var json request (most of the time)
2. there is an additional `chunksize` option for thumbnails now, that breaks down the request into smaller requests (defaults to `20`)
