### ISSUE TITLE
h5ai is not working under some server APIs (getenv() vs. $_SERVER)

### ISSUE THREAD

**Issue by Celti** [lrsjng/h5ai#539]
NearlyFreeSpeech shared hosting infrastructure uses a custom gateway interface, NFGI — blazingly fast, works quite well, but it doesn't export the values add_globals_and_envs() expects to find with getenv() into the environment, they exist solely in $_SERVER instead.

Is there a reason that h5ai does not use $_SERVER (the standard PHP interface for such things, AFAIK), or at least fall back to checking $_SERVER if getenv() returns null?

I must note that replacing the calls to getenv with $_SERVER myself has h5ai working quite well.

**Comment by lrsjng** [comment]
Fixed in latests [dev builds](https://release.larsjung.de/h5ai/develop/).
