### ISSUE TITLE
Anyway to remove Google Fonts?

### ISSUE THREAD

**Issue by jimmy19990** [lrsjng/h5ai#540]
As we know, Google is blocked in China, which makes China users experiencing unbearably slow speed when accessing h5ai. So I'm wondering whether there is a way to remove Google Fonts or replace the request with another CDN.

Thanks.

**Comment by lrsjng** [comment]
just change it in `_h5ai/private/conf/options.json` to your likings..

**Comment by jimmy19990** [comment]
That works, thanks alot!

**Comment by BenK885** [comment]
> That works, thanks alot!

Could you provide some more information, how-to remove Google Fonts in options.json?
