### ISSUE TITLE
Node 6.2.0 npm warnings

### ISSUE THREAD

**Issue by xor-gate** [lrsjng/h5ai#541]
While trying to build from source myself on Mac OS X with Homebrew (package manager) running on node 6.2.0 I get the following warnings:

```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

Thanks for your hard work on this nice indexer!
Probably you could update your README.md it also works on OS X with homebrew to build from source.

**Comment by lrsjng** [comment]
The warnings are only related to the build tool [`ghu`](https://github.com/lrsjng/ghu) not to `h5ai` itself. I have to update the deps of that build tool so everything plays nicely with `node 6`.

**Comment by xor-gate** [comment]
Yeah I understand, still warnings feels like a iron fork is poking in my eye  (-_-" OC-disorder). Thanks for fixing this to be future proof for node 6! As you talked in my other feature request to support NGINX JSON indexing or other HTTP server/application i'm trying to integrate h5ai into a monolithic application with golang so the web assets are builtin and loaded into RAM. My current work is done in custom branch https://github.com/xor-gate/h5ai/tree/golang-http-server. Then we should be able to ship h5ai as a standalone application with zero dependencies (theoretical), like [Gogs](https://gogs.io) for example.

**Comment by xor-gate** [comment]
I will close this issue, as I don't want to pollute discussion into a "real issue". Would you mind if we discus the current situation of the API/options as this needs to be partial rewritten into Golang instead of PHP (in case of the implementation I like). As there is no API documentation at-all (I digged deep into the source and found some hints, but still is feels like i'm reverse-engineering the API).

**Comment by lrsjng** [comment]
Maybe [this](https://gist.github.com/lrsjng/75f1b529a06072c2fe767de5bb03592c) will help you, but I wrote this down some months ago as I started working on a node backend. Things might change at an time..

**Comment by xor-gate** [comment]
This seems useful, of course things will change. It is not bad to have multiple backend languages/systems as this makes the frontend ui more flexibel and documented. Currently i'm a bit stuck how the options javascript object is injected into the session/page.
