### ISSUE TITLE
Wrong path in $public_href

### ISSUE THREAD

**Issue by meulie** [lrsjng/h5ai#545]
Hi,

I tried to deploy the latest version of h5ai on my server today, but it looks like the paths  various paths are no longer valid. I've tracked it down to $public_href containing the full filepath, instead of the relative server path:
what I have: https://[my.web.site]/var/www/my.web.site/htdocs/_h5ai/public/js/scripts.js
what it should be: https://[my.web.site]/_h5ai/public/js/scripts.js

using NGINX.

What did I do wrong?

**Comment by lrsjng** [comment]
@meulie just checked it with my test servers. nginx 1.7.0 and 1.10.0 work both out of the box for me.. I think most likely is a problem with your PHP<->CGI config?

**Comment by meulie** [comment]
Hmm, I haven't made any changes to the config between my previous version (which I deployed the end of January 2016), and yesterday's deploy...

What does your php<->cgi config look like on your nginx 1.10 ?

**Comment by lrsjng** [comment]
this is my [nginx config](https://gist.github.com/lrsjng/dac06c29af7293c8fc5d59f5dd6cdd32) (the relevant parts).

**Comment by jobenvil** [comment]
@meulie may I help? I have nginx 1.10 and works fine
```
root@hiperborea ~ # nginx -v
nginx version: nginx/1.10.1
```
should I post some config file or list directories?

**Comment by meulie** [comment]
It looks like the january edition worked with php-fpm & hhvm, and the new version is having issues with hhvm (or at least my hhvm-config). I've reverted back to php-fpm for now and will investigate further as soon as I have time. 

@lrsjng & @jobenvil : Thank you for your swift and friendly help  :)

**Comment by meulie** [comment]
Turned out that having the 'root' inside the location-block didn't work (anymore?). When I moved it to the server-block, all was well again  :)
