### ISSUE TITLE
h5ai with CloudFlare wont load the main page

### ISSUE THREAD

**Issue by NNickey** [lrsjng/h5ai#548]
The page shows for an instant but disappears with my website behind CloudFlare.

Fix is to disable Rocket Loader,
Rocket Loader is breaking on of the java scripts from functioning correctly.
It was applied as automatic, once set to off, the site loads fine.

![image](https://cloud.githubusercontent.com/assets/3466265/16153096/1c3209a2-3462-11e6-85f3-bf8f4c9614b1.png)

Not sure if it is a general problem with Cloudflare or could be solved by making it compatible with CloudFlare.

**Comment by lrsjng** [comment]
it seems to be a general problem with their code loader.. reported frequently, can't fix
