### ISSUE TITLE
How does "hideIf403" actually work?

### ISSUE THREAD

**Issue by thadius856** [lrsjng/h5ai#551]
Title pretty much says it all.

I have h5ai installed in nginx's root and have restricted some subfolders by forcing nginx to return a 403. When a user clicks on a folder they can't access, h5ai jumps in and lists the seemingly-empty folder to them.

Is there a way to hide these "empty" folders from being displayed altogether? Or maybe changing the folder icon to include a red 'x' or something?

Note that h5ai throws a trailing / at the end of the folder name. If I remove the trailing /, my custom 403 is displayed, so I know nginx is configured correctly.

**Comment by lrsjng** [comment]
the comment above each options block includes short descriptions for each option

> hideIf403: boolean, hide files and folders that are not readable by the server
