### ISSUE TITLE
nginx htpasswd directory h5ai don't show my files

### ISSUE THREAD

**Issue by moodcela** [lrsjng/h5ai#558]
hello :)

I use h5ai (0.28.1)
ubuntu server 16.04, nginx1.11.3,, php7-fpm

h5ai setup directory = /var/webhard/_h5ai

I hope my directory protect to
/var/webhard/test

my nginx .conf file code

server {
    listen       80;
    server_name  localhost;
	server_name 192.168.1.100;
	server_name exid.download;
	root /var/webhard;

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;

    location / {
		index  /_h5ai/public/index.php;
		}
	
	location ^~ /test {
		auth_basic "RESTRICTED ACCESS";
		auth_basic_user_file /etc/nginx/passwd/.htpasswd;
		}

I succeed protect test folder.

my h5ai website visit - 
h5ai - test folder click - id/passwd input >> test folder opened!!!

but, h5ai don't show my files. TT

test folder not empty. (but my h5ai site  don't show my files)
![test0](https://cloud.githubusercontent.com/assets/20749641/17274867/06bbfb42-572f-11e6-9bd8-06d3801d12c4.PNG)

![test](https://cloud.githubusercontent.com/assets/20749641/17274846/b1c9da1e-572e-11e6-9678-4e4dd65fbdac.PNG)
![test2](https://cloud.githubusercontent.com/assets/20749641/17274849/b483b39c-572e-11e6-80a9-763198140b01.PNG)

I hope fix it... help me T.,T
I don't speak english well... sorry TT

**Comment by jobenvil** [comment]
try to insert `index /_h5ai/public/index.php;` in `test` block

**Comment by moodcela** [comment]
I try... it index /_h5ai/public/index.php; in test block
but don't  show my files

**Comment by moodcela** [comment]
error_log

2016/07/31 20:25:37 [crit] 14764#14764: *5 open() "/etc/nginx/passwd/.htpasswd" failed (13: Permission denied), client: 192.168.1.1, server: localhost, request: "POST /test/? HTTP/1.1", host: "exid.download", referrer: "http://exid.download/test/"

**Comment by moodcela** [comment]
@jobenvil so thanks 
i fix it!!

.htpasswd permisson root root

chown www-data:www-data change

fix it 

thank you
