### ISSUE TITLE
proper installation (permissions and index file)

### ISSUE THREAD

**Issue by edmundlaugasson** [lrsjng/h5ai#562]
Which permissions should each file and folder have? Installation is not just copying files to root directory. What about hosting services where is not possible to edit web server configuration file?
How should the index file look like?

**Comment by lrsjng** [comment]
@edmundlaugasson the web server needs obviously read permissions for all files and folders in `_h5ai`. For the `cache` directories it needs write permissions. Folder `_h5ai/public` needs to be web accessible, folder `_h5ai/private` should not be web accessible.

On shared hosting services or any other hosting solution with no server config access, the only way to use h5ai is with Apache and the use of `.htaccess` to set `DirectoryIndex`.

**Comment by lapsio** [comment]
Which files have to be executable?
