### ISSUE TITLE
.htaccess with apache 2.4 

### ISSUE THREAD

**Issue by beckspaced** [lrsjng/h5ai#564]
hello there,

just found this nice little tool via google and did a fresh install on my box with apache 2.4 which immediately threw an error, e.g.

Satisfy all
Order allow,deny
Allow from all

is no longer supported by apache 2.4 without the compat module

a better option would be:

```
<IfModule !mod_access_compat.c>
    Require all granted
</IfModule>
<IfModule mod_access_compat.c>
    Order allow,deny
    Allow from all
</IfModule>
```

which would then work for old & new apache version. perhaps someone could update the .htaccess? or perhaps i could fork and create a pull request?

thanks for such a nice tool ;)

greetings
becki

**Comment by beckspaced** [comment]
ups ... it stripped out some code. must use 'insert code' button ;)

`<IfModule !mod_access_compat.c>
Require all granted
</IfModule>
<IfModule mod_access_compat.c>
Order allow,deny
Allow from all
</IfModule>`

**Comment by lrsjng** [comment]
@beckspaced  hi becki, this issue should be solved. please check one of the latest [dev builds](https://release.larsjung.de/h5ai/develop/).

**Comment by beckspaced** [comment]
great! good to know that is issue is already solved. keep up the good work ;)
