### ISSUE TITLE
Empty subfolders

### ISSUE THREAD

**Issue by MoeLoli** [lrsjng/h5ai#566]
Hello, I installed h5ai not display files and folders, I have a good set up .htaccess

**Comment by iflei** [comment]
me too. I use nginx with same problem.

**Comment by RomeSilvanus** [comment]
chmod -R 775 /your/folder/

I would also recommend chown -R www-data:www-data /path/to/_h5ai/public/cache

**Comment by iflei** [comment]
@RomeSilvanus Changed the owner and the group, Also change the permissions, But still do not display files and directories.

**Comment by JclMiku** [comment]
@RomeSilvanus I've followed the steps you did, but found or invalid

**Comment by lrsjng** [comment]
@JclMiku @iflei can you please describe your installation process?

* what does the h5ai info page show after installation?
* where did you put folder `_h5ai` and where are your own files?
* what URL are you starting with in the browser?
* do you have live links for me to check?

**Comment by julpec** [comment]
Hello

I have the same problem. I answer your questions @lrsjng 

- The H5ai info page show a big h5ai with paypal donation and login field. I have clicked on login and I see all the field in green exept php arch in 32bits (I'm under raspberrypi 2). You can check it [here](http://jopec.xilm.org/partage/_h5ai/public/index.php)
- The _h5ai folder is at the root of my apache directory. It's a test, so I have not big files. The path is /var/www/partage/_h5ai. Here is my apache conf : 
`<VirtualHost *:80>
	ServerName jopec.xilm.org
	ServerAdmin xxx@xxx
	DocumentRoot /var/www
        <Directory /var/www/partage>
                Options +Indexes +Includes +FollowSymLinks +MultiViews
                AllowOverride None
                Order allow,deny
                Allow from all
                Require all granted
                DirectoryIndex  _h5ai/public/index.php
        </Directory>
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
`
- The URL I start is : `http://jopec.xilm.org/partage` and the subfolders contains text files.

The permissions are good, all is 775 and www-data owner.

Is there a way to have log files ?

Thanks !

**Comment by lrsjng** [comment]
the leading slash is missing:

```
DirectoryIndex /_h5ai/public/index.php
               ^
```

**Comment by lrsjng** [comment]
you installed it in a subdir, so you actually have to set it to:

![screenshot_2016-12-12_22-34-38](https://cloud.githubusercontent.com/assets/181815/21117741/46c8beb4-c0bb-11e6-8b74-cb24a6f4cfa2.png)

**Comment by julpec** [comment]
Excellent ! thanks a lot, it's working !

Thanks for this work, it's really goooood !

**Comment by 872517414** [comment]
Me too.
#606

**Comment by 872517414** [comment]
h5ai need scandir passthru exec(optional) function.
