### ISSUE TITLE
h5ai 0.29.0 Chinese filename gibberish

### ISSUE THREAD

**Issue by iflei** [lrsjng/h5ai#567]
h5ai 0.29.0 Chinese filename gibberish, Unlike 0.27.0 file directory ,How to solve?

**Comment by lrsjng** [comment]
@iflei here is an example folder with [special chars](https://larsjung.de/h5ai/demo/special%20chars/%EC%95%88%EB%85%95%ED%95%98%EC%84%B8%EC%9A%94%20%EC%84%B8%EA%B3%84/) that I use for testing purposes. Can't reproduce your problems, can you give more information, on you OS, filesystem, encoding, browser, versions?

**Comment by iflei** [comment]
@lrsjng First of all thank you very much! I use Chinese, I thought it was Chinese encoding is not supported. However, not. I have found the problem, Because  before landing SFTP, I didn't set the encoding to utf-8.

**Comment by lrsjng** [comment]
@iflei so all fine now?

**Comment by iflei** [comment]
@lrsjng [I have a new problem in #569](https://github.com/lrsjng/h5ai/issues/569)
