### ISSUE TITLE
404 File not found

### ISSUE THREAD

**Issue by Evoley** [lrsjng/h5ai#568]
I installed nginx a while ago and got tired of looking at the default auto index so I decided to install h5ai. Everything went smoothly but whenever I restart nginx I get a file not found error. I have tried moving the folder to where my files are and some other stuff like redoing permissions but it just gave me a 502 error and 404. As far as I'm aware the only real error that I even see in the error.log for nginx is 

>  FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: "ip", server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/.config/php-fpm/socket:", host: "fileserver"

So i'm not entirely sure as to why it's not working. The index.php file is obviously there.

**Comment by lrsjng** [comment]
Looks more like a nginx setup problem.. nothing related to h5ai. Maybe [this](http://serverfault.com/questions/517190/nginx-1-fastcgi-sent-in-stderr-primary-script-unknown) will help you..
