### ISSUE TITLE
Password on main page

### ISSUE THREAD

**Issue by hedibf** [lrsjng/h5ai#573]
Hi, 

Is there a way to make the main page with a password request ?
Like /_h5ai/public/index.php instead of a .htaccess ?

Regards,
Hédi

**Comment by lrsjng** [comment]
No, I'm sorry...

**Comment by RomeSilvanus** [comment]
I'm kinda wondering why though. Obviously it works on the info page. Is it so easy to get around, too much work, or are you just opposed to it for other reasons?

**Comment by lrsjng** [comment]
h5ai does not serve the files, it just kicks in if there is no `index` file in a directory, to display some details on this directory. Making this kick-in page password aware would not secure your files from direct download, it would just block the listing. A lot of people didn't really understand that difference in the past, and I'm still getting mails on a regular basis why files, that are hidden in the h5ai conf, can still be accessed directly..

the best way to secure your content and use h5ai is to use your server access restrictions to secure a folder and place h5ai completely *inside* that folder.

**Comment by jobenvil** [comment]
I use this

```
auth_basic "Not currently available";
auth_basic_user_file /etc/nginx/.htpasswd;
```

i.e with NGINX:

 location / {

        # Athentication

         auth_basic "Not currently available";
         auth_basic_user_file /etc/nginx/.htpasswd;

        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        # try_files $uri $uri/ /index.html;

        #client_max_body_size   0;
        proxy_read_timeout      600;
        proxy_send_timeout      300; # chunks to server, 5 min dav

        # h5ai

        autoindex       on;
        index           index.html  index.php  /_h5ai/public/index.php;

you can follow this [tutorial to set up HTTP Authentication on NGINX](https://www.digitalocean.com/community/tutorials/how-to-set-up-http-authentication-with-nginx-on-ubuntu-12-10)

**Comment by RomeSilvanus** [comment]
Hm, okay. That's a good explanation. I didn't even think about direct downloads, for me it would've been enough to just block people from seeing it (I wouldn't need absolute security, just a fancy password page). Most of them probably don't know how to get around that anyway.

But I can see why it's not in there now.

**Comment by jobenvil** [comment]
While trying to download some file inside _h5ai:
```
root@hiperborea ~ # wget http://hiperborea.xxxxx.xx/Album/Fotos/1999/1999%20-%2012%20-%2031%20-%2023h00m56s%20-%20%20KODAK%20DC4800%20ZOOM%20DIGITAL%20CAMERA.jpg
--2016-08-17 14:10:11--  http://hiperborea.xxxx.xx/Album/Fotos/1999/1999%20-%2012%20-%2031%20-%2023h00m56s%20-%20%20KODAK%20DC4800%20ZOOM%20DIGITAL%20CAMERA.jpg
Resolving hiperborea.xxxxxx.xx (hiperborea.xxxxx.xx)... 192.168.178.50
Connecting to hiperborea.xxxxx.xx (hiperborea.xxxxx.xx)|192.168.178.50|:80... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```
While trying to download by browser I get a 401 Authorization error as well.
