### ISSUE TITLE
[Help] Unable to make latest version work, getting 403

### ISSUE THREAD

**Issue by Nihim** [lrsjng/h5ai#577]
I have been running .28 if I remember correctly on another machine and it was very straightforward to setup. So I tried to do this again today but alas I am unable to make it work.

webserver: lighttpd 1.4.33
OS: Ubuntu 14.04.5

- I am using a subdomain so I have created the relevant $HTTP["host"] for it and set a server.document-root = /var/www/h5 . _h5ai is set in /var/www/h5/_h5ai
- Subdomain works properly. 
- index-file.names is set to ( "index.php", "index.html", "index.lighttpd.html", "/_h5ai/public/index.php" )
keep in mind that when I used '/_h5ai/public/index.php' from the installation guide, lighttpd complained for invalid config
- _h5ai is owned by my user and grouped under www-data.
- Permissions are set to 775 for _h5ai/* and 740 for _h5ai/private
- There is nothing in the error.log or syslog

I get 403 on everything. If I rename the public/index.php everything is shown normally by lighttpd.
I am unable to understand what I am doing wrong and would gladly accept some pointers.

Cheers

**Comment by lrsjng** [comment]
@Nihim please try it with 755 on the private folder

**Comment by Nihim** [comment]
@lrsjng no change

```
-rw-rw-r-- 1 loke www-data 18420 Αύγ  12 14:59 _h5ai/CHANGELOG.md
-rw-rw-r-- 1 loke www-data  2755 Αύγ  12 14:59 _h5ai/README.md

_h5ai/private:
total 20
drwxr-xr-x 5 loke www-data 4096 Αύγ  22 13:13 .
drwxrwxr-x 4 loke www-data 4096 Αύγ  22 13:13 ..
drwxr-xr-x 2 loke www-data 4096 Αύγ  22 13:13 cache
drwxr-xr-x 3 loke www-data 4096 Αύγ  22 13:13 conf
drwxr-xr-x 5 loke www-data 4096 Αύγ  22 13:13 php

_h5ai/public:
total 36
drwxrwxr-x 7 loke www-data 4096 Αύγ  22 13:42 .
drwxrwxr-x 4 loke www-data 4096 Αύγ  22 13:13 ..
drwxrwxr-x 2 loke www-data 4096 Αύγ  22 13:13 cache
drwxrwxr-x 2 loke www-data 4096 Αύγ  22 13:13 css
drwxrwxr-x 2 loke www-data 4096 Αύγ  22 13:13 ext
-rw-rw-r-- 1 loke www-data  226 Αύγ  12 14:59 .htaccess
drwxrwxr-x 6 loke www-data 4096 Αύγ  22 13:13 images
-rw-rw-r-- 1 loke www-data  582 Αύγ  12 14:59 index.php
drwxrwxr-x 2 loke www-data 4096 Αύγ  22 13:13 js
```
.htaccess affects only apache right?

**Comment by lrsjng** [comment]
can you post your nginx.conf?

**Comment by Nihim** [comment]
As I mentioned in the first post it's lighttpd

```
server.modules = (
        "mod_access",
        "mod_alias",
        "mod_compress",
        "mod_redirect",
#       "mod_rewrite",
)

server.document-root        = "/var/www"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

dir-listing.encoding        = "utf-8"

index-file.names            = ( "index.php", "index.html", "index.lighttpd.html", "/_h5ai/public/index.php" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
## Use ipv6 if available
#include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

fastcgi.server             = ( ".php" =>
                               ( "localhost" =>
                                 (
                                   "socket" => "/tmp/php-fastcgi.socket",
                                   "bin-path" => "/usr/bin/php5-cgi"
                                 )
                               )
)

$HTTP["host"] =~ "(^|\.)sub\.domain\.com"{
        server.document-root = "/var/www/h5"
        dir-listing.activate = "disable"
}
```

since I did a very minimal install on that machine - so probably only what dependencies lighttpd grabbed, maybe I am missing some package?

**Comment by lrsjng** [comment]
Okay, that looks pretty standard, nothing suspicious here. I assume you already checked that PHP is working fine (e.g. with an simple PHP info script)? Next idea would then be to remove the h5ai entry from the `index-file.names` for now and check `YOUR_DOMAIN/_h5ai/public/index.php` directly in the browser, to see if you can reach the h5ai info page..

**Comment by lrsjng** [comment]
as for the htaccess files, I don't think that lighttpd supports them, but there is no app critical stuff in there, just default security stuff for apache httpd..

**Comment by Nihim** [comment]
Well yea. The version.php also got 403. So I made an empty one and it again got 403. So I looked at the config again and ....  without enabling module: mod_fastcgi it ain't gonna really going to work...

Sorry for wasting your time :/ 
Though in https://larsjung.de/h5ai/ under the lighttpd example you should change 
```
index-file.names += ('index.html', 'index.php', '/_h5ai/public/index.php')
````
to
```
index-file.names += ("index.html", "index.php", "/_h5ai/public/index.php")
```
lighttpd doesn't like ' throws: invalid character in variable name
