### ISSUE TITLE
not working 0.29 with php5.5 and apache2.2

### ISSUE THREAD

**Issue by rcyclope** [lrsjng/h5ai#580]
i have installed h5ai 0.29 but i have a probleme with the index.php chargement

when i enter my url i have ddlbox with telechergement file and no h5ai page
 like this => http://puu.sh/qSwl7/4d1864635e.png

my .htaccess : 

```
DirectoryIndex /_h5ai/public/index.php

AuthUserFile /home/xxxxxxxxx/xxxxxxxxx/.htpasswd
AuthGroupFile /dev/null
AuthName "Acces Restreint"
AuthType Basic
<Limit GET POST>
require valid-user
</Limit>
```

**Comment by MechMK1** [comment]
This looks like an issue of PHP not being correctly interpreted by the server. Do other PHP files work fine?
