### ISSUE TITLE
No thumbnails are generated

### ISSUE THREAD

**Issue by andykais** [lrsjng/h5ai#582]
My apache2 server has not generated any thumbnails. I am running with php7.0, ImageMagick and ffmpeg installed on ubuntu server, but I have not done anything to let `_h5ai` know they are installed (I know php is working at the very least because the file server is displayed properly). The whole `_h5ai` as well as the folders containing images have write access (`chmod -R 0777 .`).

I have not touched the default `private/conf/options.json`. Here is (I think) the relevant thumbnail part of the config
```
"thumbnails": {
        "enabled": true,
        "img": ["img-bmp", "img-gif", "img-ico", "img-jpg", "img-png"],
        "mov": ["vid-avi", "vid-flv", "vid-mkv", "vid-mov", "vid-mp4", "vid-mpg", "vid-webm"],
        "doc": ["x-pdf", "x-ps"],
        "delay": 1,
        "size": 240,
        "exif": false,
        "chunksize": 20
    },
```

Am I missing something? The thumbnails are just supposed to generate upon visiting the page correct?

**Comment by MechMK1** [comment]
When you access _h5ai on your webserver, you should see a login prompt and a detailled breakdown of h5ai's found modules. Can you verify if h5ai claims that it can generate thumbnails?

**Comment by andykais** [comment]
apologies for the late reply, can you clarify how to show the found modules? Do you mean typing in `exampleserver.com/_h5ai` should display a login prompt? 

Doing so only displays more of the _h5ai file manager display, although the _h5ai folder is hidden (as it should be) at the application root.

Some more info
- both `exec` and `passthru` are enabled by checking
```
if(function_exists('exec')) {
    echo "exec is enabled";
}
```
- I have installed `php-imagick`

**Comment by MechMK1** [comment]
Yes, when opening yourserver.com/_h5ai/public/, then you should see a "status page" oh h5ai.

I'd attach a screenshot, but I'm on my phone.

**Comment by andykais** [comment]
found it! OK so here is the relevant part of the mods. As you can see image thumbs is disabled, movie thumbs is enabled, but neither are showing up in the app.
![image](https://cloud.githubusercontent.com/assets/6627147/19421767/3e97d67e-93d6-11e6-9690-04545811f511.png)

**Comment by andykais** [comment]
Aha! I was missing the PHP GD program. A simple `apt-get install php-gd` solved my problems

**Comment by Arinerron** [comment]
I'm experiencing a similar issue @andykais. I'm wondering, how did you go about debugging this to discover the missing package?
