### ISSUE TITLE
How could Me to install The H5AI ?

### ISSUE THREAD

**Issue by monsterxcn** [lrsjng/h5ai#587]
Hello,I'm a Chinese student.I want to set up a website to share my files with my friend.I choose h5ai and I have been upload the installation pack.Here is it:http://cool.moccoo.cn/_h5ai/public/index.php
But what should I do next?
(I'm sorry about my pool English...)
My Email address  1206999743@qq.com  Can you send a Email to help me?Thanks a lot !
&Making friends...

**Comment by mokehow** [comment]
Something else:

Public Cache directory no

Private Cache directory no

Movie thumbs no

PDF thumbs no

Shell tar no

Shell zip no

Shell du no

**Comment by mushishi06** [comment]
i think you need to check the access's permission to http://cool.moccoo.cn for the guest (403 Forbidden)

**Comment by Dk2048** [comment]
lnmp or lamp?
you can use `chown -R www:www _h5ai`
