### ISSUE TITLE
Drag & Drop File Upload

### ISSUE THREAD

**Issue by boraguler** [lrsjng/h5ai#588]
Would love to see drag & drop file upload as a feature / extension. Although we can modify the source to accomplish this task, It'll be better to have it within package.

**Comment by mknrls** [comment]
was also thinking of this a while back but doubt he would add it like it would required some server side implementation witch he doesn't want to add. (want to keep purely as a web server index only and would also require more work on his part) 

correct me if i'm wrong @lrsjng

**Comment by RomeSilvanus** [comment]
Doesn't the extension part of h5ai provides the means to make it possible for someone to write a upload function?

**Comment by VynceCook** [comment]
It's a great app! I would love to see that feature too. Is there a way to do that thanks to html5 features without too much server side code?
