### ISSUE TITLE
How to video loop?

### ISSUE THREAD

**Issue by faq4272** [lrsjng/h5ai#596]
Is it possible to how configure h5ai the video loop? As far as I understand, h5ai used html5 video. 
Maybe is possible correct it where the player code for looping video?

**Comment by Armstrong1992** [comment]
If you want, loop every video then change "<video..." to <video loop..." in
https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/public/js/lib/ext/preview/preview-vid.js#L10

**Comment by faq4272** [comment]
OMG. Thanks man.
