### ISSUE TITLE
Can't get into info page, login loop (nginx)

### ISSUE THREAD

**Issue by razirazo** [lrsjng/h5ai#600]
Hi, im setting up the script and trying to access the info page. 
But instead of showing the info page, it keep reloading back to login page. 
Changing the password didn't help. The rest of script is working fine though.
I failed to see any problem with my Nginx config either:

```
server {
        listen       443 ssl http2;
        server_name  domain.name;
		root /home/user/downloads;
	
        location / {
			index  index.html  index.php  /_h5ai/public/index.php;
			try_files $uri $uri/ /index.html /index.php /_h5ai/public/index.php;
			auth_basic "Stahp!!!!";
			auth_basic_user_file /etc/nginx/.htpasswd;
        }
		
	location ~ \.php$ {
	    try_files $uri =404;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }	

		
    }
```

Can someone help?

**Comment by finict** [comment]
I had the same problem, but solved it by doing as follows
Change the group of this directory to users with php running
> /var/lib/php/session

example:
`sudo chown root:nginx /var/lib/php/session`
