### ISSUE TITLE
request to reduce the minimum required version of php

### ISSUE THREAD

**Issue by shantanugadgil** [lrsjng/h5ai#601]
Hi,
I used CentOS 7 and the default PHP shipped with the OS is version 5.4.16.
(I do not want to install the newer version from the SCLs)

As a test, I changed the line in "public/index.php"
`define('MIN_PHP_VERSION', '5.4.16');`

Things seem to be working fine.
Just curious why the minimum if 5.5.0 and can the default minimum be reduced '5.4.16'

Regards,
Shantanu

**Comment by AdrienPoupa** [comment]
Just curious why would you still use an old-unsupported version of PHP.

**Comment by shantanugadgil** [comment]
@AdrienPoupa  because that is the default installed version in CentOS 7.

**Comment by ideaman924** [comment]
I don't think reducing the required version will be safe in the long run. You should consider upgrading the PHP version on your machine.

A security vulnerability for your convenience does not seem right to me. Just my two cents, no offense.

**Comment by shantanugadgil** [comment]
@ideaman924 no issues, no offense taken :)

Let me explain. Its not just convenience.
From an "enterprise" perspective, why one (I) would use CentOS/RHEL is it stability and predictable configuration settings, etc.
_* I do not want to start a distro war here, its just the way things are, and that is an unending discussion._
:) :)

Sometimes, the downside of using CentOS is the not-so-quick update pace of packages.
(This is actually *fine* as what we are looking for is stability, not the latest-and-greatest version of funky-package-X)

That said, I am not saying that this PR *has* to go in, it was just a recommendation.
h5ai is an **awesome** tool and an entire distro (CentOS 7.x) gets left out due to the 5.5 requirement.
I won't be too disturbed if this PR were rejected, and that's fine.

There are ways and means to get "newer" version of software on RHEL/CentOS using the SCL repos, but they are not part of the *usual* "yum update" method.
Using SCLs seems a bit too much for this requirement.
The servers that I use are behind a firewall and used for hosting trivial (internal) things, so I won't bother to go through the possible security vulnerabilities that version 5.4.16+ may or may not have.
 
Thanks and Regards,
Shantanu

**Comment by ideaman924** [comment]
@shantanugadgil thanks for the clarification. Kind of weird CentOS doesn't update their packages as often. But that being said, this can be looked into. I'm not the official developer here so it stands moot.

**Comment by shantanugadgil** [comment]
Hi @lrsjng, any thoughts/inputs on this? 😄
