### ISSUE TITLE
HTTP 500 error

### ISSUE THREAD

**Issue by ideaman924** [lrsjng/h5ai#604]
Pretty sure I'm doing something wrong but don't know why. I'm using the Caddy docker found here:
`github.com/abiosoft/caddy-docker`

Basically, this line keeps repeating, over and over again in the error log:

```
06/Feb/2017:06:24:20 +0000 [ERROR 0 /_h5ai/public/index.php] PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function session_start() in /srv/h5ai/_h5ai/private/php/class-bootstrap.php:11
Stack trace:
#0 /srv/h5ai/_h5ai/public/index.php(17): Bootstrap::run()
#1 {main}
  thrown in /srv/h5ai/_h5ai/private/php/class-bootstrap.php on line 11
```

Would like to know what PHP extensions I'm missing. The docker is currently running on PHP 7 as you can see in this commit:

`https://github.com/abiosoft/caddy-docker/commit/1c105cdd1f06ab462ccfeb90d184e8174f7f1229`

Any insight will be appreciated. Thank you in advance!

**Comment by lrsjng** [comment]
[session_start](http://php.net/manual/en/function.session-start.php) is a built-in function in PHP 4, PHP 5 and PHP 7. If it is missing, then there seems to be something wrong with the PHP installation.

**Comment by ideaman924** [comment]
It works fine now, thanks!

**Comment by lrsjng** [comment]
@ideaman924 what was the problem?

**Comment by ideaman924** [comment]
I dunno, the problem just went away. I suspect the docker image I was using
got updated and I just didn't know.

Major thanks to the help! User environment error, problem solved.

2017. 2. 28. 오후 9:16에 "Lars Jung" <notifications@github.com>님이 작성:

**Comment by ideaman924** [comment]
One more thing. To those of you with the same problem as me, here is the commits that fixed the issue:

https://github.com/abiosoft/caddy-docker/commit/06919cdff952717c513103077bcdc7dab2bc7389

Oddly enough, in PHP7 you also need php7-session as an extension. Strange.
