### ISSUE TITLE
Internet Explorer 11 results in fallback mode

### ISSUE THREAD

**Issue by tstrotz** [lrsjng/h5ai#607]
I noticed on the project page it states, "Best user experience with the latest versions of Chrome, Firefox, Opera, Vivaldi, Safari and Edge, but a static fallback is provided for older browsers or if JavaScript is disabled.". I'm using Internet Explorer 11 in Windows 10 with JavaScript enabled which is resulting in the page being displayed in fallback mode. Is Internet Explorer 11 not supported? Is there any possible workaround to disable fallback mode in the PHP and if so, where would I find that variable? Thanks!

**Comment by tstrotz** [comment]
No ideas??

**Comment by lrsjng** [comment]
Internet Explorer 11 is not supported, sry
