### ISSUE TITLE
File management

### ISSUE THREAD

**Issue by homlett** [lrsjng/h5ai#608]
That would be very cool if h5ai could manage files (upload, delete and rename/move mainly), even through dedicated plugins. Could it be possible to easily add a simple upload functionality with https://github.com/blueimp/jQuery-File-Upload for example or it's much more complicated?

**Comment by RomeSilvanus** [comment]
I case this gets declined, and you want a lightweight solution, I'd suggest using [Caddy](https://caddyserver.com) for this.

It's very easy to set-up, and if you use the [filemanager module](https://caddyserver.com/docs/filemanager) you get a very nice and responsive web interface for managing your files.

![filemanager](https://cloud.githubusercontent.com/assets/7461492/23118031/e4f67cb6-f752-11e6-98e9-610da58e7db2.png)

**Comment by lil5** [comment]
I suggest https://github.com/dom111/webdav-js
