### ISSUE TITLE
h5ai dosen't list files

### ISSUE THREAD

**Issue by MatYRicS** [lrsjng/h5ai#610]
Hi,

After a few hours of trying to get this up and running I'm giving up. I have installed h5ai and when I access MY_DOMAIN/_h5ai/public/index.php every step is green.

My nginx conf:

```
        location /test {
                root /config/www;
                index  /_h5ai/public/index.php;
                autoindex on;
                }
```

When I access MY_DOMAIN/test the webserver is up and running with h5ai but it just say that the directory is empty. 

![](https://i.imgur.com/pvFSjnd.jpg)

I have checked my php.ini file and no functions are disabled either.

Any ideas how to fix this issue?

**Comment by Lrs121** [comment]
I think you're missing some things from the index line.

The h5ai website lists this as the configuration:
`index  index.html  index.php  /_h5ai/public/index.php;
`

**Comment by tac00** [comment]
@Lrs121 I have tried that line too but there is still no files in MY_DOMAIN/test

**Comment by Lrs121** [comment]
Ah ok, that's weird.

I'm not sure if docker would cause an issue. I'm not very familiar with how docker mounts directories. The problem may be related to how h5ai doesn't really like aliases. I have the same issue with a direct from host apache web server and userdirs.

![screenshot from 2017-03-03 18-30-47](https://cloud.githubusercontent.com/assets/3093776/23575394/12f4fa5c-0040-11e7-9115-666404d97acb.png)

**Comment by tac00** [comment]
I have tried to install a h5ai docker image and run it in its own container and it works fine. So its probaly not something to do with Docker. Im not using alias I'm pointing the location to another root dir which should work fine for h5ai according to many other users. 

I have moved to Pydio  instead of nginx+h5ai.
