### ISSUE TITLE
Thumbnails don't load

### ISSUE THREAD

**Issue by menyf** [lrsjng/h5ai#614]
Sorry to disturb.

The version of h5ai I'm using is the latest -- v0.29

I think everything should be good.

When I check`my.site.com/_h5ai/public/index.php`, the item "Image thumbs" returns "yes".

```
h5ai version 0.29.0
Only green if this is an official h5ai release
Index file found yes
Add /_h5ai/public/index.php to your index file list
Options parsable yes
File options.json is readable and syntax is correct
Types parsable yes
File types.json is readable and syntax is correct
Server software apache
Server is one of apache, lighttpd, nginx or cherokee
PHP version 5.6.27
PHP version >= 5.5.0
PHP arch 64-bit
64-bit required to correctly display file/folder sizes > ~2GB
Public Cache directory no
Web server has write access
Private Cache directory no
Web server has write access
Image thumbs yes
PHP GD extension with JPEG support available
Use EXIF thumbs yes
PHP EXIF extension available
Movie thumbs no
Command line program avconv or ffmpeg available
PDF thumbs no
Command line program convert or gm available
Shell tar no
Command line program tar available
Shell zip no
Command line program zip available
Shell du no
Command line program du available
```

And `thumbnails` in  `my.site.com/_h5ai/private/conf/options.conf` remains default, which is

```
"thumbnails": {
        "enabled": true,
        "img": ["img-bmp", "img-gif", "img-ico", "img-jpg", "img-png"],
        "mov": ["vid-avi", "vid-flv", "vid-mkv", "vid-mov", "vid-mp4", "vid-mpg", "vid-webm"],
        "doc": ["x-pdf", "x-ps"],
        "delay": 1,
        "size": 240,
        "exif": false,
        "chunksize": 20
    },
```

And I can find ALL thumbs right in the folder `my.site.com/_h5ai/public/cache/thumbs`

However, when I visit my website, it doesn't display, when I check the HTML, every `<img>` label is `<img src="/_h5ai/public/images/fallback/file.png" alt="file"/>`

Should I do some other configurations?  How can I make the generated thumbs display?

Thank you.

**Comment by jobenvil** [comment]
just an Idea; check that the rights are for execute:
```
drwxrwxr-x 9 root     www-data 4096 Jul 29  2016 Uploader
drwxrwxr-x 2 root     www-data 4096 Aug  3  2016 Public
drwxrwxr-x 4 root     www-data 4096 Aug  3  2016 Server Infos
drwxr-xr-x 4 root     www-data 4096 Aug 13  2016 _h5ai
```

**Comment by menyf** [comment]
Thanks for your reply. 

It seems that I have already solved this issue. But I didn't know which step worked.

1. make php support `exec`
2. `rm -r _h5ai` then redownload and unzip
3. add rights
`chmod 777 _h5ai/public/cache` 
`chmod 777 _h5ai/private/cache`

Maybe step 3 is the key.

**Comment by kongr45gpen** [comment]
For future reference, another issue that might cause thumbnails not to work is if **PHP-GD is not installed**.

A `sudo apt install php-gd` should fix this on Ubuntu.

**Comment by Arinerron** [comment]
For me the reason why thumbnails weren't working was because the thumbnail cache directory didn't have write perms.
```
chmod a+rw _h5ai/public/cache _h5ai/private/cache
```
