### ISSUE TITLE
h5ai able to work on windows/apache/russian environment? 

### ISSUE THREAD

**Issue by UksusoFF** [lrsjng/h5ai#615]
Hi!

I can't configure h5ai to work on this environment:
Windows 8.1
WAMP Server (Apache/2.4.9, PHP/5.5.12)
It's possible?

Russian folders shown as percent encoded. And there empty. English named folders same empty.

![image](https://cloud.githubusercontent.com/assets/1931442/24525564/d00cb8b6-15ab-11e7-808d-3df88c7ff8bf.png)

After this patch #612 it's correctly show russian folder names. But russian and english folder still empty.

![image](https://cloud.githubusercontent.com/assets/1931442/24525526/aaba083e-15ab-11e7-8b0b-8eb18082a040.png)

It's Apache alias config:

```
Alias /demo "G:/!Photo/photo_pub/demo/" 

<Directory "G:/!Photo/photo_pub/demo/">
    AddDefaultCharset UTF-8 
    Options FollowSymLinks MultiViews Indexes
    IndexOptions Charset=UTF-8

    AllowOverride all
    Order allow,deny
    Allow from all

    DirectoryIndex  index.html  index.php  \_h5ai\public\index.php
</Directory>
```

**Comment by Mxy123h** [comment]
`return Util::normalize_path($this->setup->get('ROOT_PATH') . '/' . rawurldecode($rel_href));` to 

`return Util::normalize_path($this->setup->get('ROOT_PATH') . '/' . mb_convert_encoding(rawurldecode($rel_href), $nonUtf8Charset, "UTF-8"));`
