### ISSUE TITLE
Problem in multiple virtual host

### ISSUE THREAD

**Issue by YnievesDotNet** [lrsjng/h5ai#616]
I have some virtualhosts, 2 oh then using h5ai, but, en both case show me the last directory, no the correspondent directory

/home/site1/
-----_h5ai/
-----filesOnSite1

/home/site2/
-----_h5ai/
-----filesOnSite2

I call both sites, in the browser and only show the filesOnSite2, in both cases

Yoinier

**Comment by Armstrong1992** [comment]
Could you please post Vhost configuration?

**Comment by YnievesDotNet** [comment]
Is problem of apache, and debian, I install centos and now work fine.

Thanks, Yoinier.

2017-04-27 4:39 GMT-04:00 Paweł Smok <notifications@github.com>:
