### ISSUE TITLE
How to set hidden some file type

### ISSUE THREAD

**Issue by isxiao** [lrsjng/h5ai#625]
How to set hidden some file type such *.aria2  or  *.torrent and so on?

**Comment by tosih** [comment]
https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/private/conf/options.json#L40

**Comment by isxiao** [comment]
I know "hidden": ["^\\.", "^_h5ai"] can be use to hide files.
^_h5ai means file name started by _h5ai, but i don't know how to set file name ended by torrent.
I have tried *.aria2 or *.torrent  but didn't work.

**Comment by mushishi06** [comment]
hi,
use `["^\.", "^_h5ai", ".torrent$"]`
the `$` at the ends of the string you want.
Work for me
