### ISSUE TITLE
Broken Korean language on text file preview

### ISSUE THREAD

**Issue by awesometic** [lrsjng/h5ai#626]
Please see this.

![issue](https://user-images.githubusercontent.com/10906167/27951010-6413e662-633e-11e7-9a05-936d920fcaf0.PNG)

How can I fix it?
There's nothing wrong on file index pages. But when I see preview of text file involving Korean, it shows like above image.

Thanks to provide this amazing application. Could you fix this?

**Comment by obbcth** [comment]
메모장에서 저장할 때 UTF-8로 저장하는 옵션 있습니다. 아니면 Notepad++를 쓰시면 되고요.
Save text file by using utf-8 in notepad, or use Notepad++.

**Comment by awesometic** [comment]
Thanks, I thought the encoding method it uses but I didn't test well. I will test very carefully next time.
