### ISSUE TITLE
PHP Fatal error execution time exceeded on big directories

### ISSUE THREAD

**Issue by lapsio** [lrsjng/h5ai#629]
When listing directory with 8600 files I'm getting following errors:

    [Wed Jul 26 20:26:06.021349 2017] [php5:error] [pid 32498] [client 127.0.0.1:38616] PHP Fatal error:  
    Maximum execution time of 30 seconds exceeded in /srv/www/htdocs/h5ai/_h5ai/private/php/core/class-
    item.php on line 26, referer: https://-----.-----.----/----/----/----/
    [Wed Jul 26 20:26:37.249369 2017] [php5:error] [pid 32499] [client 127.0.0.1:38624] PHP Fatal error:  
    Maximum execution time of 30 seconds exceeded in /srv/www/htdocs/h5ai/_h5ai/private/php/core/class-
    item.php on line 20, referer: https://-----.-----.----/----/----/----/

Related to #628 being general scalabilily issue.

I tried increasing nginx connection alive time and apache max php time to 1000s but browsers seem to have own timeout limit as well so it didn't help.

**Comment by lapsio** [comment]
Performance decrease is caused by cache mechanism - particularly checking whether file exists in cache. After removing checks performance is good enough to operate on significantly bigger directories.

**Comment by jobenvil** [comment]
I'm interested which lines where you deleted. Thanks

**Comment by lapsio** [comment]
This is my current class-item.php. I don't remember which lines were changed but you can run `diff` against original file. I added additional parameter to skip checking only on big directories. On huge directories I also disabled meta checking because it's slow on synchronously mount NFS mountpoints.

    <?php
    
    class Item {
        public static function cmp($item1, $item2) {
            if ($item1->is_folder && !$item2->is_folder) {
                return -1;
            }
            if (!$item1->is_folder && $item2->is_folder) {
                return 1;
            }
    
            return strcasecmp($item1->path, $item2->path);
        }
    
        public static function get($context, $path, &$cache, $skip_meta) {
    
            if (!Util::starts_with($path, $context->get_setup()->get('ROOT_PATH'))) {
                return null;
            }
    
            $item = new Item($context, $path, $skip_meta);
    
            $cache[$path] = $item;
            return $item;
        }
    
        public $context;
        public $path;
        public $href;
        public $date;
        public $size;
        public $is_folder;
        public $is_content_fetched;
    
        private function __construct($context, $path, $skip_meta) {
            $this->context = $context;
    
            $this->path = Util::normalize_path($path, false);
            $this->is_folder = is_dir($this->path);
            $this->href = $context->to_href($this->path, $this->is_folder);
        if (!$skip_meta){
    //          syslog(LOG_ERR,"PathMeta:".$path);
    
                $this->date = @filemtime($this->path);
                $this->size = Util::filesize($context, $this->path);
        } else {
    //          syslog(LOG_ERR,"Path:".$path);
        }
    
            $this->is_content_fetched = false;
        }
    
        public function to_json_object() {
            $obj = [
                'href' => $this->href,
                'time' => $this->date * 1000, // seconds (PHP) to milliseconds (JavaScript)
                'size' => $this->size
            ];
    
            if ($this->is_folder) {
                $obj['managed'] = $this->context->is_managed_href($this->href);
                $obj['fetched'] = $this->is_content_fetched;
            }
    
            return $obj;
        }
    
        public function get_parent(&$cache) {
            $parent_path = Util::normalize_path(dirname($this->path), false);
            if ($parent_path !== $this->path && Util::starts_with($parent_path, $this->context->get_setup()->get('ROOT_PATH'))) {
                return Item::get($this->context, $parent_path, $cache);
            }
            return null;
        }
    
        public function get_content(&$cache) {
            $items = [];
    
            if (!$this->context->is_managed_href($this->href)) {
                return $items;
            }
    
            $files = $this->context->read_dir($this->path);
        $skip_meta = (count($files)>10000?true:false);
    
            foreach ($files as $file) {
                $item = Item::get($this->context, $this->path . '/' . $file, $cache, $skip_meta);
                $items[$item->path] = $item;
            }
    
            $this->is_content_fetched = true;
    
            return $items;
        }
    }

**Comment by jobenvil** [comment]
thanks @lapsio

**Comment by biast12** [comment]
i'm getting this error rn but in `class-filesize.php`, line 46 to be specific

i have tried
```
ini_set('max_execution_time', '9999999999');
set_time_limit(9999999999);
```
and it does make it load, but it does take ages loading, note that my files are around 618 GB in total, + i am already using [#771](https://github.com/lrsjng/h5ai/pull/771)
