### ISSUE TITLE
Shell zip, Shell Du not working

### ISSUE THREAD

**Issue by x8BitRain** [lrsjng/h5ai#633]
I'm on Ubuntu server 17.04 trying to enable shell-zip so I can download folders in zip format.
I've removed shell_exec from disabled functions in the php.ini (yes the one that's loaded).
I've made a symlink and tried copying zip to the same location that tar is in.
I've tried giving nginx (www) permissions to own/execute/anything to zip in both locations.
Also tried chmod 777ing zip, still says shell zip and shell du are not available. 

What else can I try?

**Comment by RomeSilvanus** [comment]
Maybe install php7.0-zip / php7.1-zip / php7.2-zip.

Also php7.x-gd regarding thumbs.

**Comment by x8BitRain** [comment]
php7.0-zip and php-zip are installed, php7.1-zip has no installation candidate, php7.2-zip doesn't seem to exist. I'm using php 7.1.8 and tried installing php7.1-zip via deb and it didn't work. Still no luck.
