### ISSUE TITLE
File/Folder sizes based on 1000

### ISSUE THREAD

**Issue by Jisagi** [lrsjng/h5ai#640]
As the title already says, i can't get the size to show based on 1024 so everything is larger than it actually is.

I checked `_h5ai/public/index.php` and i have `64bit php-arch` with `php v7.0.23-1~dotdeb+8.1` and `apache v2.4.10` on `h5ai v0.29.0`

Is this a problem in my side (config/software) or a h5ai problem?

**Comment by lrsjng** [comment]
use this option

https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/private/conf/options.json#L62

**Comment by Jisagi** [comment]
@lrsjng Perfect, thank you!
Maybe i should've searched for '1024' in the options.json and not just '1000' :sweat_smile:
