### ISSUE TITLE
All the requierements are green?

### ISSUE THREAD

**Issue by Ventix** [lrsjng/h5ai#641]
All is green:
https://ventix.eu/public/

And now? 

I cant find the password string in "private/conf/options.json".

**Comment by lrsjng** [comment]
Please follow the install instructions here: https://larsjung.de/h5ai/

1. Copy folder `_h5ai` (not only the content of it, but the folder itself) to the document root directory of the web server: `DOC_ROOT/_h5ai`.

3. Add `/_h5ai/public/index.php` (note the leading slash!) to the end of the default index-file list. In this way h5ai will manage all directories in and below DOC_ROOT that don't have a index file.

**Comment by lrsjng** [comment]
The password hash is the very first entry in the options file:

https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/private/conf/options.json#L8

**Comment by Ventix** [comment]
I have followed the instructions???

**Comment by lrsjng** [comment]
Please copy the **folder** named **_h5ai** into your root directory *not* only it's content, but the folder itself.

**Comment by Ventix** [comment]
in which root directory can i chat at keybase?
