### ISSUE TITLE
worked fine on nginx, now broken on apache

### ISSUE THREAD

**Issue by coosnake** [lrsjng/h5ai#645]
As title says.
I setup nginx on Apache and the pages are blank. Same for other people.
The page source shows all the code but the result remains blank.

I don't have a lot of experience with this, anything obvious?

**Comment by Armstrong1992** [comment]
Nginx as proxy for apache or standalone? Please provide vhost conf and list of files in vhost directory.

**Comment by coosnake** [comment]
Oops, I made a mistake in my post. I meant to write h5ai, not nginx. I used to have h5ai working fine on nginx and made the switch to apache and now have the problem aforementioned.

**Comment by Armstrong1992** [comment]
Anything in Error logs?
