### ISSUE TITLE
ServiceWorker sw.js error

### ISSUE THREAD

**Issue by mrunc** [lrsjng/h5ai#651]
Hi, I have this simple configuration with Nginx and PHP 7.0.26 I'm getting lots of these errors

In FireFox 

     Failed to register/update a ServiceWorker for scope ‘https://data.xxxxx.com/’: Load failed with status 404 for script ‘https://data.xxxxx.com/sw.js’.

In error log

    2018/01/06 21:15:31 [error] 15368#15368: *1 open() "/data/server/sw.js" failed (2: No such file or directory), client: xx.xx.67.76, server: data.xxxx.com, request: "GET /sw.js HTTP/2.0", host: "data.xxxx.com"

I have h5ai installed in /data/server/_h5ai/ and my root dir for nginx is  /data/server/

here is my nginx config

      server {
      
        listen 80;
        server_name data.xxxxx.com;
        return 301 https://$server_name$request_uri;
      }
      
      server {
      
        listen          443 ssl http2;
        server_name     data.xxxxx.com;
      
        ssl_certificate /etc/letsencrypt/live/data.xxxxx.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/data.xxxx.com/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/data.xxxx.com/fullchain.pem;
         
        ssl_client_certificate /opt/server/certs/rootCA.crt;
        ssl_crl /opt/server/crl/ca.crl;
        ssl_verify_client on;
         
        include snippets/ssl-params.conf;
      
        root /data/server;
      
        error_log /var/log/nginx/h5ai_error.log;
      
        location / {
          index index.html index.php /_h5ai/public/index.php;
          autoindex on;
          try_files $uri $uri/ =404;
          
        }
      
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_pass   php-fpm;
            fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
      }

**Comment by mrunc** [comment]
The slow loading issue is resolved if I disable thumbnails in _h5ai/private/conf/options.json 
But i'm still getting these errors

In FireFox 

     Failed to register/update a ServiceWorker for scope ‘https://data.xxxxx.com/’: Load failed with status 404 for script ‘https://data.xxxxx.com/sw.js’.

In error log

    2018/01/06 21:15:31 [error] 15368#15368: *1 open() "/data/server/sw.js" failed (2: No such file or directory), client: xx.xx.67.76, server: data.xxxx.com, request: "GET /sw.js HTTP/2.0", host: "data.xxxx.com"

**Comment by mrunc** [comment]
I tried to give write permission to www-data on /data/server/ but it didn't fix the error

**Comment by lrsjng** [comment]
@mrunc Hi, this `sw.js` file is not part of h5ai.. does neither provide nor request such a file

**Comment by mrunc** [comment]
Something messed up just happened it was other script that I installed before on same vhost and completely removed from server but firefox kept requesting this specific file for it
just clearing cache and cookies for the sub-domain fixed the issue
