### ISSUE TITLE
How to hide all the files in a directory

### ISSUE THREAD

**Issue by lzyroot** [lrsjng/h5ai#652]
How to hide all the files in a directory

Thank you!

**Comment by Armstrong1992** [comment]
Add it to options.json under view section.
```json
"view": {
        "hidden": ["^\\.", "^_h5ai", "^foldertohide"],
```

**Comment by Maubry94** [comment]
Hi! I want to hide a certain type of file in all my folders except one. Is that possible?

**Comment by Maubry94** [comment]
Nvm. I forgot to escape the "/".
