### ISSUE TITLE
I am beginner, can you teach me how to build this h5ai step by step on localhost

### ISSUE THREAD

**Issue by joekempis** [lrsjng/h5ai#653]

**Comment by Armstrong1992** [comment]
By "build" you mean from source? It is pretty simple you just need nodejs and then use:
 ```
> npm install
> npm run build
```
while in main directory.

**Comment by joekempis** [comment]
im just downloaded from this link https://release.larsjung.de/h5ai/

and i want to know the next step installing on localhost.

**Comment by Armstrong1992** [comment]
Please read: https://larsjung.de/h5ai/

**Comment by joekempis** [comment]
im still don't understand how to step by step

**Comment by CrashLaker** [comment]
Hello. 

I just ran `npm run build`.
What's next? Do I have to point apache to it? To which dir?

**Comment by CrashLaker** [comment]
This helped me https://larsjung.de/h5ai/. 

Now it's working

thank you :)
