### ISSUE TITLE
h5ai suddenly in fallback mode?

### ISSUE THREAD

**Issue by chippey5** [lrsjng/h5ai#656]
Hi,

I had h5ai running just fine for a week and suddenly it fell back to Apache's vanilla webserver interface. I thought it had something to do with one of the folders containing too many files (1100), so I excluded the thumbnail generation as suggested in [https://github.com/lrsjng/h5ai/issues/377](url) in options.json. Issue remained. Removed older files in the directory so that I had 300 left, restarted apache. Issue remained. 

It all happened suddenly, as if it was in fallback mode. When trying to open localhost/_h5ai/public/index.php it says "404 object not found", while it is existing there. Other folders are displayed in the parent directory. I activated errorlogs for PHP, but none were generated. 

Any ideas?

**Comment by Armstrong1992** [comment]
Can you show vHost configuration?
