### ISSUE TITLE
How to keep the custom site name?

### ISSUE THREAD

**Issue by SunZhizhong** [lrsjng/h5ai#657]
I want to customize the site name, which is displayed on my browser tab, but after I've modified index.php's information, the site name can only last for a while, and then the default domain name will be restored.
How can I keep a custom site name?

**Comment by Armstrong1992** [comment]
Change from `true` to `false`
https://github.com/lrsjng/h5ai/blob/44e53ab213d37f45df2acac01e957c67ec06f8a7/src/_h5ai/private/conf/options.json#L368-L373

**Comment by SunZhizhong** [comment]
[https://sunmusic.download/QQ%E6%88%AA%E5%9B%BE20180208214330.png](url)
Thank you, the browser title bar has been, I would like to ask two other places how to deal with?

**Comment by Armstrong1992** [comment]
Two options:
1: Changing `location.getDomain()` to `'Somtehing I want'` and building from sources:
https://github.com/lrsjng/h5ai/blob/44e53ab213d37f45df2acac01e957c67ec06f8a7/src/_h5ai/public/js/lib/model/item.js#L120
2. Editing already builded `_h5ai/public/js/scripts.js` and replacing
```js
"/"===e?f.getDomain():n.name
```
To
```js
"/"===e?'Something I want':n.name
```

**Comment by SunZhizhong** [comment]
I use h5ai0.29.0, the first method does not "item.js" this file, the second method has not changed after the change ... Thank you for your help.

**Comment by Armstrong1992** [comment]
It has to be caching issue. Use new private window or clear browser cache (mostly Ctrl+F5)

**Comment by SunZhizhong** [comment]
![qq 20180209193644](https://user-images.githubusercontent.com/26864064/36026097-9a9b0a66-0dd0-11e8-95e5-c9ebf47ebfd9.png)
Sorry, I tried a lot of ways, to visit, but the name has not changed.

**Comment by Armstrong1992** [comment]
When you open: `https://your.domain/_h5ai/public/js/scripts.js` change to the file is presented?

**Comment by SunZhizhong** [comment]
Yes! finally! The original CDN cache scripts.js file, so when I visit https: //your.domain/_h5ai/public/js/scripts.js inside the setting has not changed, I will scripts.js removed from the CDN cache After that, the name is correct! once again! Thank you very much for your help! !

**Comment by Armstrong1992** [comment]
I'm glad that I've helped. Please close the issue. Thanks.
