### ISSUE TITLE
Preview issue with selection

### ISSUE THREAD

**Issue by macbem** [lrsjng/h5ai#661]
In previews, you can't select text via mouse. It's because `mousedown` and `mousemove` events are assigned a `dropEvent` handler. This causes natural movements that usually select text to be ignored.

Is there any reason behind this? I changed these `dropEvent` handlers to just do `event.stopPropagation()` instead of `event.stopPropagation()` and `event.preventDefault()`, which allows the user to select stuff again.

IMO this should be reverted.

**Comment by drejom** [comment]
@macbem any chance you could provide some more details for this fix? Its an issue for me too
