### ISSUE TITLE
How can I add a header or footer?

### ISSUE THREAD

**Issue by SupremeLiam** [lrsjng/h5ai#667]
Since I am a freshman, I'd like to know where the `_h5ai.headers.html` or `_h5ai.footers.html` to put.
I've read `options.json`, but after I've tried several times, there is no change on my h5ai page.
What's more, if there is a javascript in HTML, will it be shown?
I need a more specific example.
Thank you.

**Comment by Armstrong1992** [comment]
Answering the question: No, Js is not executed in header or footer.

Example of using headers (same apply to footers):

```
.
├── _h5ai
│   ├── private
│   └── public
│   └── .htaccess
├── my music
│   ├── test.mp3
│   ├── sing.mp3
│   ├── record.mp3
│   └── _h5ai.header.html
├── my video
│   ├── video.mp4
│   └── record.mp4
├── test.txt
└──  _h5ai.headers.html
```
`my music` will use content of `_h5ai.header.html` and `my video` will use `_h5ai.headers.html` (note the letter `s`!)

**Comment by whiskeyfur** [comment]
@SupremeLiam You're missing the underscore ( _ ) character in front of the file names, otherwise the _h5ai.header.html and _h5ai.footer.html go in the SAME directory you want to build the listing for. That is probably why they were not showing up.

You're almost there.

**Comment by bigrain1993** [comment]
意思就是fooder和header必须都要有，页面才会有效果
