### ISSUE TITLE
The symbolic link folder don't show in h5ai website.

### ISSUE THREAD

**Issue by NEOherozzz** [lrsjng/h5ai#671]
Hello,

I add a symbolic link in the root directory of the web server, but it  doesn't list in the website. How should I do if I want to add a folder index in another directory?

Thanks

**Comment by Armstrong1992** [comment]
Linux, Windows?  Using relative, hard link, soft link, bind mount? Permissions?

**Comment by Vivalemuc** [comment]
I have the same problem ;)

I have a directory with many files, i put a symlik in h5ai directory, but when i navigate on this folder on the website, a blank page is retrieved !
It's work with standard directory ! It's just this symlik directory !

**Comment by BiatuAutMiahn** [comment]
Same issue here on windows, tried junction, symbolic link, and even volume mountpoint. When folder sizes was enabled, PHP was iterating through the drives so I disabled that for speed...and no files to show.

**Comment by gitsang** [comment]
Check the permition, h5ai is using `www-data` user

Symlink file from /root or change file mod to 0700 will hide folder from web.

eg.

- `ln -s /root/file /var/www/h5ai` can not show
- `ln -s /file /var/www/h5ai` can show
- `drwx------ 4 root root  4096 Nov 30 14:09 file` can not show
- `drwx------ 4 www-data www-data  4096 Nov 30 14:09 file` can show
