### ISSUE TITLE
Cache zip files and tarballs

### ISSUE THREAD

**Issue by LNJ2** [lrsjng/h5ai#672]
I've got some folders which are about 1-30 GB large, unfortunately h5ai will generate tarballs and zip files on the fly (it generates them locally, blocks every other request and then answers the GET request and then deletes the file). It'd be great if the archives would get cached and not regenerated every time (disk space is not a problem in my case).

**Comment by Joemag** [comment]
h5ai sends the archive directly to the browser, without ever writing it to disk, and there usually would be no big benefit of caching it. 

If you have many small files, caching could improve response time. In this case you can just create an archive yourself and put it on the server.

> blocks every other request and then answers the GET request

Thats a different issue: #326 
A workaround is removing the line `session_start();` from [_h5ai/private/php/class-bootstrap.php#L11](https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/private/php/class-bootstrap.php#L11)

**Comment by LNJ2** [comment]
Thanks for your answer. After using shell-zip, the performance somehow is much much better now, so this problem is solved for me. :smile:
