### ISSUE TITLE
putenv() has been disabled for security reasons

### ISSUE THREAD

**Issue by EmanDev** [lrsjng/h5ai#675]
(i'm very new to this)
I was experimenting with h5ai by hosting it on 000webhost. It worked pretty well later on I received this  error:

Warning
: putenv() has been disabled for security reasons in
/storage/ssd4/393/6082393/public_html/_h5ai/private/php/class-bootstrap.php
on line
8

errors can also be found from this similar site: https://andreito-2006-games.000webhostapp.com/Juegos/Boton%28Button%29/

**Comment by EmanDev** [comment]
**Update** 
I commented out line 8 which contains:

putenv('LANG=en_US.UTF-8');
to 
//putenv('LANG=en_US.UTF-8');

and it works again.

**Comment by qrqhuang** [comment]
in `php.ini` , find config item `disable_functions`  and remove `putenv`.

**Comment by qrqhuang** [comment]
@lrsjng I'm glad to see u come back, continue maintenance this project~
