### ISSUE TITLE
你的程序很好用。能播放flv，mp4，但是avi，wma文件没法播放，有法解决吗？

### ISSUE THREAD

**Issue by aff2018** [lrsjng/h5ai#684]
你的程序很好用。能播放flv，mp4，

但是avi，wma文件没法播放，有法解决吗？

**Comment by eluotao** [comment]
avi，wma . 没法直接播放,但是可以设置跳转到其他网址播放.

**Comment by orangeff** [comment]
> avi，wma . 没法直接播放,但是可以设置跳转到其他网址播放.

那么该怎么做呢

**Comment by anbo225** [comment]
播放格式取决于浏览器的支持，建议使用ffmpeg将视频转换为flv，MP4格式，这样就可以用vps下载播放电影了
