### ISSUE TITLE
Anyone is maintaining this beautiful project?

### ISSUE THREAD

**Issue by shirshak55** [lrsjng/h5ai#685]
Otherwise someone has to maintain it :D

**Comment by danieltroger** [comment]
@shirshak55 Do it!

**Comment by shirshak55** [comment]
@danieltroger yeah will maintain it  will start probably after month . This month too much work load:)

**Comment by Daniel15** [comment]
@lrsjng Do you have any plans for maintenance of h5ai? If not, what about moving it to a Github org and adding some more maintainers?

**Comment by shirshak55** [comment]
Sorry guys i completely forgot about it . I will start updating the code and if possible i will use rust instead of PHP. 

I will let u know once done. Currently I cannot give eta :)

**Comment by shirshak55** [comment]
atm i will close this issue is abit irrelevant.

**Comment by shirshak55** [comment]
It seems like Irsing is back :)

Thanks.
