### ISSUE TITLE
Warning: require_once(): open_basedir restriction in effect. File

### ISSUE THREAD

**Issue by Latezly** [lrsjng/h5ai#686]
Warning: require_once(): open_basedir restriction in effect. File(/www/wwwroot/192.168.2.104/_h5ai/private/php/class-bootstrap.php) is not within the allowed path(s): (/www/wwwroot/192.168.2.104/_h5ai/public/:/tmp/:/proc/) in /www/wwwroot/192.168.2.104/_h5ai/public/index.php on line 16

Warning: require_once(/www/wwwroot/192.168.2.104/_h5ai/private/php/class-bootstrap.php): failed to open stream: Operation not permitted in /www/wwwroot/192.168.2.104/_h5ai/public/index.php on line 16

Fatal error: require_once(): Failed opening required '/www/wwwroot/192.168.2.104/_h5ai/public/../private/php/class-bootstrap.php' (include_path='.:/www/server/php/56/lib/php') in /www/wwwroot/192.168.2.104/_h5ai/public/index.php on line 16

-------------------------------------------------------------------------------------------------------------------

I used the bt panel（https://www.bt.cn/） to build the lnmp environment. After all the rest of the operations are completed, open the website to display this error.

**Comment by shirshak55** [comment]
it is permission problem

**Comment by shirshak55** [comment]
first change to user to  :www-data And then change permission to 755 after that you can move to secure permission again
