### ISSUE TITLE
h5ai网页标题会自动变成当前网站域名如何修改

### ISSUE THREAD

**Issue by lzyroot** [lrsjng/h5ai#689]
各位大佬们

**Comment by Ninzero** [comment]
去 _h5ai/public/js/scripts.js 里面找, 有个部分是 `f.getDomain():n.name` 把 `f.getDomain()` 改成你想要的字符串即可. 举例来说 `"lzyroot":n.name`.

**Comment by Ninzero** [comment]
抱歉, 这样做实际上是修改了根目录的名称, 准确的做法应当是编辑 /_h5ai/private/conf/options.json, 里面有个部分是 `title` 把 `"enabled": true` 改为 false, 这样网页标题就不会被自动修改了. 随后编辑 _h5ai/private/php/pages/index.php 中 `<title>index - powered by h5ai v0.29.2 (https://larsjung.de/h5ai/)</title>` 的部分即可, 举例来说 `<title>lzyroot</title>`

**Comment by lzyroot** [comment]
谢谢

**Comment by jinzhijie** [comment]
突然冒出个中文的吓我一跳，正好是我要找的，谢谢大佬

**Comment by zhangjycf** [comment]
> 去_h5ai/public/js/scripts.js里面找，露出的部分是`f.getDomain():n.name`把`f.getDomain()`改成你想要的字符串抓取。举例说明`"lzyroot":n.name`。

您好，我根目录名称修改后不成功，30版本的，"/"===f?p.getDomain():n.name修改成了“/"==="/":n.name
