### ISSUE TITLE
Public cache directory

### ISSUE THREAD

**Issue by mlmmilkyway** [lrsjng/h5ai#693]
hi new h5ai site, can't get folders to list in web page, also says Public Cache directory not writable even after doing chmod 777 to the folder

http://data.globalecology.unh.edu/_h5ai/public/index.php

running Scientific Linux 7.6, with nginx 1.14.1, h5ai 0.29.0, php 7.2.10

What should I look at next?

Mark

**Comment by lrsjng** [comment]
Make sure `public/cache` and `private/cache` are writable

**Comment by rdaems** [comment]
I fixed this by changing ownership of `_h5ai` to `www-data`:

`sudo chown -R www-data:www-data _h5ai/`
