### ISSUE TITLE
h5ai CentOS 8 PHP 7.2.11 don't work

### ISSUE THREAD

**Issue by cloverkits** [lrsjng/h5ai#718]
![32D300D0C88EB9A394FD5DB5B1FC23FF](https://user-images.githubusercontent.com/20393492/65602648-cf92a380-dfd6-11e9-9bfb-847d51df9d20.jpg)
![4D9842BB652BA494F252846AEB80CB71](https://user-images.githubusercontent.com/20393492/65602671-dd482900-dfd6-11e9-8bae-b7e868b942a6.jpg)
![7DB4C5C939B741878FFF864BF44DA553](https://user-images.githubusercontent.com/20393492/65602672-dde0bf80-dfd6-11e9-8031-9a974d6b1f13.jpg)

**Comment by protectedMan** [comment]
i has same issues

**Comment by protectedMan** [comment]
you need `yum install mod_php`

**Comment by cloverkits** [comment]
> you need `yum install mod_php`

but, don't work

**Comment by cloverkits** [comment]
![Screen Shot 2019-11-10 at 15 52 04](https://user-images.githubusercontent.com/20393492/68540759-1515ff00-03d2-11ea-8d0d-bcfb88137fb7.png)

**Comment by protectedMan** [comment]
原因应该是缺少某种扩展

**Comment by cloverkits** [comment]
> 原因应该是缺少某种扩展

自从升级到 CentOS 8 就不能用了

**Comment by anderskristoffer** [comment]
In the same boat with CentOS 8 and 7.2.11.... 

After enabling error messages in php i get the following error: 

Fatal error: Uncaught Error: Call to undefined function json_decode() in /var/www/html/_h5ai/private/php/core/class-request.php:7 Stack trace: #0 /var/www/html/_h5ai/private/php/class-bootstrap.php(14): Request->__construct(Array, '') #1 /var/www/html/_h5ai/public/index.php(17): Bootstrap::run() #2 {main} thrown in /var/www/html/_h5ai/private/php/core/class-request.php on line 7

Might give someone a hint on what is wrong

Any recomended OS / LAMP versions I could use for trouble-free install?

**Comment by thomo** [comment]
My steps to run it on CentOS 8 with apache:
- install `dnf install php-json`
- give write access to h5ai cache directory 
   - `chmod 755 _h5ai/private/cache`
   - `chown apache:apache _h5ai/private/cache`

**Comment by Gigi-Yang** [comment]
哈哈哈，用英语聊了半天，发现是中国人

**Comment by Gigi-Yang** [comment]
不过@thomo是大哥，安装了php-json扩展之后就可以了
