### ISSUE TITLE
Litespeed

### ISSUE THREAD

**Issue by Raintek** [lrsjng/h5ai#720]
Dear Developer,
does h5ai work on Litespeed servers?

**Comment by istiak101** [comment]
@Raintek yes I am using it in OpenLiteSpeed Server.

**Comment by Raintek** [comment]
> @Raintek yes I am using it in OpenLiteSpeed Server.

Could you tell me how did you do this? I tried on 3 litespeed servers, and everywhere same problem that h5ai is not working properly. Missing icons, links, etc.

**Comment by RafaelDeJongh** [comment]
> @Raintek yes I am using it in OpenLiteSpeed Server.

A lot like myself have the same issue that they can't host it on litespeed, so how exactly did you manage it?
