### ISSUE TITLE
Movie thumbs, How to define a path for ffmpeg

### ISSUE THREAD

**Issue by Machou** [lrsjng/h5ai#724]
Hello =)

I can't install ffmpeg on my server because i'm on mutu.

So i have download ffmpeg compiled with [FFmpeg Static Builds](https://johnvansickle.com/ffmpeg/). It work good with cli (i have access to ssh).

So my question is, **how in h5ai, how to define where the ffmpeg binary is located**?

Thanks

**Comment by Machou** [comment]
anyone ?

**Comment by glubsy** [comment]
h5ai seems to simply use whatever it finds in the $PATH environment variable. So whatever is returned by `which ffmpeg` will be the binary file called.

You could also hack the php script directly and replace the first item in the $FFMPEG_CMDV array with the full path to your executable file, i.e. `'ffmpeg'` -> `'/my/custom/path/to/ffmpeg'`.
