### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by KeSaite** [lrsjng/h5ai#730]
When I use h5ai to download more than 1g files, it will fail. If I use nginx to download normally, why?

![1](https://user-images.githubusercontent.com/13944595/75096259-dbf84800-55d8-11ea-83e3-746d151cb2f5.gif)

**Comment by kbeflo** [comment]
Check your nginx and php logs. You could be reaching `max_execution_time` on default php config. 

https://stackoverflow.com/q/47832929/10025507

Could also be something similar to Nextcloud cutting off at 1G

https://github.com/nextcloud/server/issues/5390

**Comment by KeSaite** [comment]
thanks
