### ISSUE TITLE
Shared hosting installation issue

### ISSUE THREAD

**Issue by nbnrvtn** [lrsjng/h5ai#737]
Hi Lrsjng,

I've followed all instructions on https://larsjung.de/h5ai/ but I still have the default Apache Index displaying. I must be missing some crucial step(s).

This is on an OVH shared hosting with PHP 7.2 (only "leeway" is .htaccess file).
Installation of h5ai is done on a sub-directory `?/home/ftp_username/sub_folder/share/_h5ai` with a subdomain poiting to `share/` and the main website under `?/home/ftp_username/sub_folder/www/`.
h5ai version is 0.29.2.

1. Downloaded the zip, extracted and copied the `_h5ai` folder to my subdomain target using FileZilla.
2. Checked `../_h5ai/public/index.php`: everything is green except PHP arch (32bit) and Movie thumbs (no).
3. Modified .htaccess file in _h5ai so it is `DirectoryIndex index.html index.php /sub_folder/share/_h5ai/public/index.php`

When I access my target folder from a browser I still have the original Apache Index displaying..

I tried almost all options on step 3: `/_h5ai/public/index.php` or even `/home/ftp_username/sub_folder/share/_h5ai/public/index.php` but nothing seems to work.

What have I done wrong?

**Comment by Umbyology** [comment]
Per the instructions under step #3: You should have a hidden file ".htaccess" located in your root directory. Paste the following anywhere in the file ... 

`DirectoryIndex  index.html  index.php  /_h5ai/public/index.php`

**Comment by gamersalpha** [comment]
Hello this u have the solution here : 

https://github.com/lrsjng/h5ai/issues/738

**Comment by nbnrvtn** [comment]
Hi! I resolved my issue which was due to a misunderstanding of the installation instructions (step 3): I had modified the `.htaccess` file in the `_h5ai` folder instead of creating a new one in the target folder (`share/` in my case).

Thank you for your help!
