### ISSUE TITLE
Permission Denied.

### ISSUE THREAD

**Issue by LifeOfJona** [lrsjng/h5ai#751]
Despite following all the steps It's lead me to see this following error:
![image](https://user-images.githubusercontent.com/44353899/92523607-a7538300-f1ee-11ea-9e60-588a3a850d7f.png)

Mind helping me out with this?

Thanks.

**Comment by glubsy** [comment]
You don't provide enough information for people to even try helping you...

**Comment by LifeOfJona** [comment]
> You don't provide enough information for people to even try helping you...

Lol. I think I was just really upset and frustrated which just made me forget to say anything. 

Closing this for now.
