### ISSUE TITLE
Unchecked l10n input leads to arbitrary JSON file reads

### ISSUE THREAD

**Issue by Yesterday17** [lrsjng/h5ai#760]
Good day:)

I'm playing a CTF game which consists of a problem using h5ai as file index program. The intended solution was related to some Nginx stuff but I've got a chance to look up into h5ai source code in detail. (Shamelessly copied from #758 :smile: )

When aduiting code, I found this problem:

https://github.com/lrsjng/h5ai/blob/d81d8a929815016e0b4e2ad2a2cdfd671d4c9330/src/_h5ai/private/php/core/class-context.php#L226-L236

Line 230 spliced the string without processing the input. Then `Json::load` used the spliced path to load and parse file using 
 `file_get_contents`. So attackers can read any JSON file there. For example, they can read options saved in `private/options.json`.

The payload looks like this:
```bash
curl 'http://202.38.93.111:10120/Public/?' \
  --data-binary '{"action":"get","l10n": ["../options"]}' \
  --compressed \
  --insecure
```

**Comment by DanielRuf** [comment]
I have contacted the maintainer regarding this and https://github.com/lrsjng/h5ai/issues/758.

See also https://github.com/lrsjng/h5ai/issues/758#issuecomment-761829414
