### ISSUE TITLE
[Debian 9.13 + php7.4] Works best with JavaScript enabled!

### ISSUE THREAD

**Issue by jedineofr** [lrsjng/h5ai#776]
Hello.

I have a problem with h5ai that displays the following error: 
_Works best with JavaScript enabled!_

I have _php7.4_ installed with the _php7.4-json_ package

> root@debian-Dedibox:/home/jedineofr# php -v
PHP 7.4.14 (cli) (built: Jan 12 2021 14:00:40) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

> root@debian-Dedibox:/home/jedineofr# apt install php7.4-json
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
php7.4-json is already the newest version (7.4.14-1+0~20210112.34+debian9~1.gbpaa175a).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 1 non mis à jour.
root@debian-Dedibox:/home/jedineofr#`

**What can I do?**

Thank you

**Comment by glubsy** [comment]
Perhaps you have blocked javascript in your browser?

**Comment by jedineofr** [comment]
I use firefox with the key
> javascript.enabled | true

**Comment by jedineofr** [comment]
I found a solution.

I modified my apache config by changing the root path
