### ISSUE TITLE
Issues during installation

### ISSUE THREAD

**Issue by Oshekher** [lrsjng/h5ai#789]
![Screenshot_20210601-071024](https://user-images.githubusercontent.com/67940483/120254894-764d3e00-c2a8-11eb-9967-5337e9bb3d0b.png)

Followed all the steps written but still I am having problem here. please check it out. For more information regarding my issues please check the screenshot which I have provided.

**Comment by glubsy** [comment]
How exactly do you expect anyone to help you with so little information?

You are missing the listed programs. Install them, make sure they can be discovered by your server (i.e. in the PATH).
