### ISSUE TITLE
h5ai & Lightspeed

### ISSUE THREAD

**Issue by RafaelDeJongh** [lrsjng/h5ai#814]
I couldn't directly find a thing about it, but I recently switched to a lightspeed server stack and while it's tons better for lots of sites, h5ai doesn't appear to be working completely with it.

Has there ever been an investigation for this or got a solution to make h5ai work within a lightspeed server stack?

Thanks in advance for any further information as I currently only get these kind of pages when I try to go to my data storage utilising h5ai.

![screencapture-data-rafaeldejongh-data-h5ai-public-index-php-2021-09-22-21_34_31](https://user-images.githubusercontent.com/4523615/134409923-692f6496-1114-4f6e-a43e-7674a92e1d5d.png)

**Comment by jerry1333** [comment]
I'm also waiting for support for lightspeed :)

**Comment by corsicanu** [comment]
If anyone is still into this and didn't find the answer yet, 
in _h5ai/private/php/core/class-setup.php replace 

`$this->set('H5AI_HREF', Util::normalize_path(dirname(dirname($script_name)), true));`

with

`$this->set('H5AI_HREF', "/_h5ai/");`

I found it somewhere and it worked, i run it on litespeed now without any issues.
Regards

**Comment by RafaelDeJongh** [comment]
Weird thing, I got it working some time after originally posting this, bug completely forgot how I resolved it. Might be the same source where the previous poster referred to or something completely else.

But well it does work on Litespeed at this time.
