### ISSUE TITLE
common ask question：how to reset the password

### ISSUE THREAD

**Issue by 775838893** [lrsjng/h5ai#835]
i was forgot the password when enter the manage page,is there a way to reset the password?
![image](https://user-images.githubusercontent.com/7666283/163532224-ecafaeee-a97a-4459-9f72-01755391c0ef.png)

**Comment by dleovl** [comment]
Open `/private/conf/options.json` in your h5ai installation. You will need to get the SHA512 hash of the new password you want to use, and place it inside the `passhash` quote.

**Comment by 775838893** [comment]
Thanks.
