### ISSUE TITLE
Errors messages 

### ISSUE THREAD

**Issue by patchint** [lrsjng/h5ai#839]
Hi,
I'm getting theses errors 
```

Warning
: file_put_contents(/application/marisa.patchli.fr/_h5ai/private/cache/cmds.json): Failed to open stream: Read-only file system in
/application/marisa.patchli.fr/_h5ai/private/php/core/class-json.php
on line
18


Warning
: Cannot modify header information - headers already sent by (output started at /application/marisa.patchli.fr/_h5ai/private/php/core/class-json.php:18) in
/application/marisa.patchli.fr/_h5ai/private/php/pages/index.php
on line
1
```

php-fpm 8
nginx version: nginx/1.23.1

**Comment by FeskVulpse** [comment]
I'm sorry that you're just now getting a response over a year later, but I really hope you figured out that this is a permission issue. Please try correcting it by giving the webserver read+write permissions to `_h5ai/private`

**Comment by patchint** [comment]
Hi ! 

My configurations changed a lot after my post !

I'm going to retest it :p

**Comment by patchint** [comment]
I've gave him the permissions but it's still not working at all

**Comment by patchint** [comment]
I close this issue after more than a year...
