### ISSUE TITLE
Show text under content menu if text file is named X (Like README.md here on github)

### ISSUE THREAD

**Issue by biast12** [lrsjng/h5ai#864]
Hey this is a feature request if someone wanna look into adding this feature, this feature would be an option to show the text of a specific text file that could be picked in the config, kinda like the README.md system here on github, this would be perfect to give details about the content of X folder and would elevate customization on a greater level

**Comment by glubsy** [comment]
Worth looking into, but I'm not sure if I'll have time to work on this in the near future. Feel free to have a hack at it though!

**Comment by biast12** [comment]
i did try to have a look at it but i nether have enough JS experience or know enough about the code of h5ai to really know what i'm doing, i understand tho and i don't think you should push yourself if you don't have time, just wanted to let you know in case you wanted to work on it

**Comment by biast12** [comment]
i'm an idiot, this is already supported with footers
